/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for DevicesPublishedAfterDate429ErrorException type.
 */
public class DevicesPublishedAfterDate429ErrorException extends ApiException {
    private static final long serialVersionUID = 4880437333315727684L;
    private int status;
    private String title;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public DevicesPublishedAfterDate429ErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Status.
     * @return Returns the int
     */
    @JsonGetter("status")
    public int getStatus() {
        return this.status;
    }

    /**
     * Setter for Status.
     * @param status Value for int
     */
    @JsonSetter("status")
    private void setStatus(int status) {
        this.status = status;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    private void setTitle(String title) {
        this.title = title;
    }

    /**
     * Converts this DevicesPublishedAfterDate429ErrorException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DevicesPublishedAfterDate429ErrorException [" + "statusCode=" + getResponseCode()
                + ", message=" + getMessage() + ", status=" + status + ", title=" + title + "]";
    }
}
