/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.http.request;

import io.apimatic.coreinterfaces.http.Method;

/**
 * HTTP methods enumeration.
 */
public enum HttpMethod implements Method {
    GET,
    POST,
    PUT,
    PATCH,
    DELETE,
    HEAD
}
