/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro;

/**
 * Interface for defining the behavior of CustomHeader Authentication.
 */
public interface CustomHeaderAuthenticationCredentials {

    /**
     * String value for xApiKey.
     * @return xApiKey
     */
    String getXApiKey();

    /**
     * Checks if provided credentials matched with existing ones.
     * @param xApiKey String value for credentials.
     * @return true if credentials matched.
     */
    boolean equals(String xApiKey);
}
