/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro;

import cloud.greenbyte.intro.apis.AlertsApi;
import cloud.greenbyte.intro.apis.AssetsApi;
import cloud.greenbyte.intro.apis.ConfigurationdataApi;
import cloud.greenbyte.intro.apis.DataApi;
import cloud.greenbyte.intro.apis.PlanApi;
import cloud.greenbyte.intro.apis.PredictApi;
import cloud.greenbyte.intro.apis.StatusesApi;
import cloud.greenbyte.intro.authentication.CustomHeaderAuthenticationManager;
import cloud.greenbyte.intro.authentication.CustomHeaderAuthenticationModel;
import cloud.greenbyte.intro.http.client.HttpCallback;
import cloud.greenbyte.intro.http.client.HttpClientConfiguration;
import cloud.greenbyte.intro.http.client.ReadonlyHttpClientConfiguration;
import cloud.greenbyte.intro.logging.configuration.ApiLoggingConfiguration;
import cloud.greenbyte.intro.logging.configuration.ReadonlyLoggingConfiguration;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Gateway class for the library.
 * This class acts as a factory for Apis.
 * It holds the state of the SDK.
 */
public final class GreenbyteClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private DataApi data;
    private StatusesApi statuses;
    private ConfigurationdataApi configurationdata;
    private AssetsApi assets;
    private AlertsApi alerts;
    private PlanApi plan;
    private PredictApi predict;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "Java-SDK/2.2.0-beta (OS: {os-info}, Engine: {engine}/{engine-version})";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The customer sub-domain
     */
    private final String customer;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * Logging Configuration instance.
     */
    private final ReadonlyLoggingConfiguration loggingConfig;

    /**
     * CustomHeaderAuthenticationManager.
     */
    private CustomHeaderAuthenticationManager customHeaderAuthenticationManager;

    /**
     * The instance of CustomHeaderAuthenticationModel.
     */
    private CustomHeaderAuthenticationModel customHeaderAuthenticationModel;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications = new HashMap<String, Authentication>();

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private GreenbyteClient(Environment environment, String customer, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig,
            ReadonlyLoggingConfiguration loggingConfig,
            CustomHeaderAuthenticationModel customHeaderAuthenticationModel,
            HttpCallback httpCallback) {
        this.environment = environment;
        this.customer = customer;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.loggingConfig = loggingConfig;
        this.httpCallback = httpCallback;

        this.customHeaderAuthenticationModel = customHeaderAuthenticationModel;

        this.customHeaderAuthenticationManager = new CustomHeaderAuthenticationManager(
                customHeaderAuthenticationModel);
        this.authentications.put("ApiKeyHeaderAuth", customHeaderAuthenticationManager);

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .loggingConfiguration(((ApiLoggingConfiguration) loggingConfig).getConfiguration())
                .build();
        data = new DataApi(globalConfig);
        statuses = new StatusesApi(globalConfig);
        configurationdata = new ConfigurationdataApi(globalConfig);
        assets = new AssetsApi(globalConfig);
        alerts = new AlertsApi(globalConfig);
        plan = new PlanApi(globalConfig);
        predict = new PredictApi(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of DataApi.
     * @return data
     */
    public DataApi getDataApi() {
        return data;
    }

    /**
     * Get the instance of StatusesApi.
     * @return statuses
     */
    public StatusesApi getStatusesApi() {
        return statuses;
    }

    /**
     * Get the instance of ConfigurationdataApi.
     * @return configurationdata
     */
    public ConfigurationdataApi getConfigurationdataApi() {
        return configurationdata;
    }

    /**
     * Get the instance of AssetsApi.
     * @return assets
     */
    public AssetsApi getAssetsApi() {
        return assets;
    }

    /**
     * Get the instance of AlertsApi.
     * @return alerts
     */
    public AlertsApi getAlertsApi() {
        return alerts;
    }

    /**
     * Get the instance of PlanApi.
     * @return plan
     */
    public PlanApi getPlanApi() {
        return plan;
    }

    /**
     * Get the instance of PredictApi.
     * @return predict
     */
    public PredictApi getPredictApi() {
        return predict;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The customer sub-domain
     * @return customer
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * Logging Configuration instance.
     * @return loggingConfig
     */
    public ReadonlyLoggingConfiguration getLoggingConfig() {
        return loggingConfig;
    }

    /**
     * The credentials to use with CustomHeaderAuthentication.
     * @return customHeaderAuthenticationCredentials
     */
    public CustomHeaderAuthenticationCredentials getCustomHeaderAuthenticationCredentials() {
        return customHeaderAuthenticationManager;
    }

    /**
     * The auth credential model for CustomHeaderAuthentication.
     * @return the instance of CustomHeaderAuthenticationModel
     */
    public CustomHeaderAuthenticationModel getCustomHeaderAuthenticationModel() {
        return customHeaderAuthenticationModel;
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        parameters.put("customer",
                new SimpleEntry<Object, Boolean>(this.customer, false));
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://{customer}.greenbyte.cloud/api/2";
            }
        }
        return "https://{customer}.greenbyte.cloud/api/2";
    }

    /**
     * Converts this GreenbyteClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GreenbyteClient [" + "environment=" + environment + ", customer=" + customer
                + ", httpClientConfig=" + httpClientConfig + ", loggingConfig=" + loggingConfig
                + ", authentications=" + authentications + "]";
    }

    /**
     * Builds a new {@link GreenbyteClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link GreenbyteClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.customer = getCustomer();
        builder.httpClient = getHttpClient();
        builder.customHeaderAuthenticationCredentials(getCustomHeaderAuthenticationModel()
                .toBuilder().build());
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(() -> ((HttpClientConfiguration) httpClientConfig).newBuilder());
        builder.loggingConfig(() -> ((ApiLoggingConfiguration) loggingConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link GreenbyteClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private String customer = "intro";
        private HttpClient httpClient;
        private CustomHeaderAuthenticationModel customHeaderAuthenticationModel =
                new CustomHeaderAuthenticationModel.Builder("").build();
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();
        private ApiLoggingConfiguration.Builder loggingConfigBuilder = null;


        /**
         * Credentials setter for CustomHeaderAuthenticationCredentials.
         * @param customHeaderAuthenticationModel The instance of CustomHeaderAuthenticationModel.
         * @return The current instance of builder.
         */
        public Builder customHeaderAuthenticationCredentials(
                CustomHeaderAuthenticationModel customHeaderAuthenticationModel) {
            this.customHeaderAuthenticationModel = customHeaderAuthenticationModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The customer sub-domain
         * @param customer The customer for client.
         * @return Builder
         */
        public Builder customer(String customer) {
            this.customer = customer;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration, takes in an operation to be
         * performed on the builder instance of logging configuration.
         * @param action Consumer for the builder of LoggingConfiguration.
         * @return Builder
         */
        public Builder loggingConfig(Consumer<ApiLoggingConfiguration.Builder> action) {
            if (loggingConfigBuilder == null) {
                loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            }

            if (loggingConfigBuilder.build().getLogger() == null) {
                loggingConfigBuilder.useDefaultLogger();
            }

            action.accept(loggingConfigBuilder);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration with Console Logging.
         *
         * @return Builder
         */
        public Builder loggingConfig() {
            loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            loggingConfigBuilder.useDefaultLogger();
            return this;
        }

		/**
		 * Private setter for the Builder of LoggingConfiguration, takes in an operation to be
		 * performed on the builder instance of logging configuration.
		 * 
		 * @param supplier Supplier for the builder of LoggingConfiguration.
		 * @return Builder
		 */
		private Builder loggingConfig(Supplier<ApiLoggingConfiguration.Builder> supplier) {
			loggingConfigBuilder = supplier.get();
			return this;
		}

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Private Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param supplier Supplier for the builder of httpClientConfiguration.
         * @return Builder
         */
        private Builder httpClientConfig(Supplier<HttpClientConfiguration.Builder> supplier) {
            httpClientConfigBuilder = supplier.get();
            return this;
        }

        /**
         * Builds a new GreenbyteClient object using the set fields.
         * @return GreenbyteClient
         */
        public GreenbyteClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            ReadonlyLoggingConfiguration loggingConfig = loggingConfigBuilder != null ? loggingConfigBuilder.build() 
                    : new ApiLoggingConfiguration.Builder().build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new GreenbyteClient(environment, customer, httpClient, httpClientConfig,
                    loggingConfig, customHeaderAuthenticationModel, httpCallback);
        }
    }
}