/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models.containers;

import cloud.greenbyte.intro.ApiHelper;
import cloud.greenbyte.intro.models.TaskAssigneeManufacturer;
import cloud.greenbyte.intro.models.TaskAssigneeOther;
import cloud.greenbyte.intro.models.TaskAssigneePersonnel;
import cloud.greenbyte.intro.models.TaskAssigneeUser;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for one-of types.
 */
@JsonDeserialize(using = TaskAssignee.TaskAssigneeDeserializer.class)
public abstract class TaskAssignee {
    
    /**
     * This is TaskAssigneeUser case.
     * @param taskAssigneeUser TaskAssigneeUser value for taskAssigneeUser.
     * @return The TaskAssigneeUserCase object.
     */
    public static TaskAssignee fromTaskAssigneeUser(TaskAssigneeUser taskAssigneeUser) {
        return taskAssigneeUser == null ? null : new TaskAssigneeUserCase(taskAssigneeUser);
    }

    /**
     * This is TaskAssigneePersonnel case.
     * @param taskAssigneePersonnel TaskAssigneePersonnel value for taskAssigneePersonnel.
     * @return The TaskAssigneePersonnelCase object.
     */
    public static TaskAssignee fromTaskAssigneePersonnel(
            TaskAssigneePersonnel taskAssigneePersonnel) {
        return taskAssigneePersonnel == null ? null : new TaskAssigneePersonnelCase(taskAssigneePersonnel);
    }

    /**
     * This is TaskAssigneeManufacturer case.
     * @param taskAssigneeManufacturer TaskAssigneeManufacturer value for taskAssigneeManufacturer.
     * @return The TaskAssigneeManufacturerCase object.
     */
    public static TaskAssignee fromTaskAssigneeManufacturer(
            TaskAssigneeManufacturer taskAssigneeManufacturer) {
        return taskAssigneeManufacturer == null ? null : new TaskAssigneeManufacturerCase(taskAssigneeManufacturer);
    }

    /**
     * This is TaskAssigneeOther case.
     * @param taskAssigneeOther TaskAssigneeOther value for taskAssigneeOther.
     * @return The TaskAssigneeOtherCase object.
     */
    public static TaskAssignee fromTaskAssigneeOther(TaskAssigneeOther taskAssigneeOther) {
        return taskAssigneeOther == null ? null : new TaskAssigneeOtherCase(taskAssigneeOther);
    }

    /**
     * This is Object case.
     * @param object Object value for object.
     * @return The ObjectCase object.
     */
    public static TaskAssignee fromObject(Object object) {
        return object == null ? null : new ObjectCase(object);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for one-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R taskAssigneeUser(TaskAssigneeUser taskAssigneeUser);

        R taskAssigneePersonnel(TaskAssigneePersonnel taskAssigneePersonnel);

        R taskAssigneeManufacturer(TaskAssigneeManufacturer taskAssigneeManufacturer);

        R taskAssigneeOther(TaskAssigneeOther taskAssigneeOther);

        R object(Object object);
    }

    /**
     * This is a implementation class for TaskAssigneeUserCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "TaskAssigneeUser")
    private static class TaskAssigneeUserCase extends TaskAssignee {

        @JsonValue
        private TaskAssigneeUser taskAssigneeUser;

        TaskAssigneeUserCase(TaskAssigneeUser taskAssigneeUser) {
            this.taskAssigneeUser = taskAssigneeUser;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.taskAssigneeUser(this.taskAssigneeUser);
        }

        @JsonCreator
        private TaskAssigneeUserCase(JsonNode jsonNode) throws IOException {
            this.taskAssigneeUser = ApiHelper.deserialize(jsonNode,
                TaskAssigneeUser.class);
        }

        @Override
        public String toString() {
            return taskAssigneeUser.toString();
        }
    }

    /**
     * This is a implementation class for TaskAssigneePersonnelCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "TaskAssigneePersonnel")
    private static class TaskAssigneePersonnelCase extends TaskAssignee {

        @JsonValue
        private TaskAssigneePersonnel taskAssigneePersonnel;

        TaskAssigneePersonnelCase(TaskAssigneePersonnel taskAssigneePersonnel) {
            this.taskAssigneePersonnel = taskAssigneePersonnel;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.taskAssigneePersonnel(this.taskAssigneePersonnel);
        }

        @JsonCreator
        private TaskAssigneePersonnelCase(JsonNode jsonNode) throws IOException {
            this.taskAssigneePersonnel = ApiHelper.deserialize(jsonNode,
                TaskAssigneePersonnel.class);
        }

        @Override
        public String toString() {
            return taskAssigneePersonnel.toString();
        }
    }

    /**
     * This is a implementation class for TaskAssigneeManufacturerCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "TaskAssigneeManufacturer")
    private static class TaskAssigneeManufacturerCase extends TaskAssignee {

        @JsonValue
        private TaskAssigneeManufacturer taskAssigneeManufacturer;

        TaskAssigneeManufacturerCase(TaskAssigneeManufacturer taskAssigneeManufacturer) {
            this.taskAssigneeManufacturer = taskAssigneeManufacturer;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.taskAssigneeManufacturer(this.taskAssigneeManufacturer);
        }

        @JsonCreator
        private TaskAssigneeManufacturerCase(JsonNode jsonNode) throws IOException {
            this.taskAssigneeManufacturer = ApiHelper.deserialize(jsonNode,
                TaskAssigneeManufacturer.class);
        }

        @Override
        public String toString() {
            return taskAssigneeManufacturer.toString();
        }
    }

    /**
     * This is a implementation class for TaskAssigneeOtherCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "TaskAssigneeOther")
    private static class TaskAssigneeOtherCase extends TaskAssignee {

        @JsonValue
        private TaskAssigneeOther taskAssigneeOther;

        TaskAssigneeOtherCase(TaskAssigneeOther taskAssigneeOther) {
            this.taskAssigneeOther = taskAssigneeOther;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.taskAssigneeOther(this.taskAssigneeOther);
        }

        @JsonCreator
        private TaskAssigneeOtherCase(JsonNode jsonNode) throws IOException {
            this.taskAssigneeOther = ApiHelper.deserialize(jsonNode,
                TaskAssigneeOther.class);
        }

        @Override
        public String toString() {
            return taskAssigneeOther.toString();
        }
    }

    /**
     * This is a implementation class for ObjectCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "Object")
    private static class ObjectCase extends TaskAssignee {

        @JsonValue
        private Object object;

        ObjectCase(Object object) {
            this.object = object;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.object(this.object);
        }

        @JsonCreator
        private ObjectCase(JsonNode jsonNode) throws IOException {
            this.object = jsonNode;
        }

        @Override
        public String toString() {
            return object.toString();
        }
    }

    /**
     * This is a custom deserializer class for TaskAssignee.
     */
    protected static class TaskAssigneeDeserializer
            extends JsonDeserializer<TaskAssignee> {

        @Override
        public TaskAssignee deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(TaskAssigneeUserCase.class,
                    TaskAssigneePersonnelCase.class, TaskAssigneeManufacturerCase.class,
                    TaskAssigneeOtherCase.class, ObjectCase.class), true);
        }
    }

}
