/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.authentication;

/**
 * A data class for Custom Header Signature credentials.
 */
public class CustomHeaderAuthenticationModel {
    private String xApiKey;

    /**
     * A Constructor for CustomHeaderAuthenticationModel.
     */
    private CustomHeaderAuthenticationModel(String xApiKey) {
        this.xApiKey = xApiKey;
    }

    /**
     * Getter for xApiKey.
     * @return xApiKey The value of X-Api-Key.
     */
    public String getXApiKey() {
        return this.xApiKey;
    }

    /**
     * Builds a new {@link CustomHeaderAuthenticationModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link CustomHeaderAuthenticationModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getXApiKey());
    }

    /**
     * A Builder class for Custom Header Signature credentials.
     */
    public static class Builder {
        private String xApiKey;

        /**
         * The constructor with required auth credentials.
         * @param xApiKey The value of XApiKey.
         */
        public Builder(String xApiKey) {
            if (xApiKey == null) {
                throw new NullPointerException("XApiKey cannot be null.");
            }

            this.xApiKey = xApiKey;
        }

        /**
         * Setter for xApiKey.
         * @param xApiKey The value of X-Api-Key.
         * @return Builder The current instance of Builder.
         */
        public Builder xApiKey(String xApiKey) {
            if (xApiKey == null) {
                throw new NullPointerException("XApiKey cannot be null.");
            }

            this.xApiKey = xApiKey;
            return this;
        }

        /**
         * Builds the instance of CustomHeaderAuthenticationModel using the provided credentials.
         * @return The instance of CustomHeaderAuthenticationModel.
         */
        public CustomHeaderAuthenticationModel build() {
            return new CustomHeaderAuthenticationModel(xApiKey);
        }
    }
}