/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.apis;

import cloud.greenbyte.intro.ApiHelper;
import cloud.greenbyte.intro.DateTimeHelper;
import cloud.greenbyte.intro.Server;
import cloud.greenbyte.intro.exceptions.ApiException;
import cloud.greenbyte.intro.exceptions.PredictAlerts400ErrorException;
import cloud.greenbyte.intro.exceptions.PredictAlerts429ErrorException;
import cloud.greenbyte.intro.http.request.HttpMethod;
import cloud.greenbyte.intro.http.response.ApiResponse;
import cloud.greenbyte.intro.models.PredictAlertsResponse;
import cloud.greenbyte.intro.models.PredictSeverity;
import cloud.greenbyte.intro.models.PredictStatus;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class PredictApi extends BaseApi {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public PredictApi(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Gets a list of Predict alerts based on filter criteria. The timestamps are in the time zone
     * configured in the Greenbyte Platform. Use the useUtc flag to get timestamps in UTC. _🔐 This
     * endpoint requires the **Predict** endpoint permission._ _This is a beta feature. Some details
     * might change before it is released as a stable version._.
     * @param  deviceIds  Required parameter: What devices to get alerts for.
     * @param  timestampStart  Required parameter: The beginning of the time interval to get data
     *         for (inclusive), in [RFC 3339, section
     *         5.6](https://tools.ietf.org/html/rfc3339#section-5.6) **date-time** format: *
     *         Timestamps ending with 'Z' are treated as UTC. Example: "2020-01-01T00:00:00Z" * Time
     *         zone (UTC) offset timestamps ending with '+HH:mm'/"-HH:mm" are also supported.
     *         Example: "2020-01-01T02:00:00-02:00" * Other timestamps are treated as being in the
     *         time zone configured in the Greenbyte Platform. Example: "2020-01-01T00:00:00" The
     *         start timestamp **is** included in the time interval: for example, to select the full
     *         month of March 2020, set `timestampStart` to "2020-03-01T00:00:00" and `timestampEnd`
     *         to "2020-04-01T00:00:00". Timestamps selected in the portal will by default be in
     *         UTC.
     * @param  timestampEnd  Required parameter: The end of the time interval to get data for
     *         (exclusive), in [RFC 3339, section
     *         5.6](https://tools.ietf.org/html/rfc3339#section-5.6) **date-time** format: *
     *         Timestamps ending with 'Z' are treated as UTC. Example: "2020-01-01T00:00:00Z" * Time
     *         zone (UTC) offset timestamps ending with '+HH:mm'/"-HH:mm" are also supported.
     *         Example: "2020-01-01T02:00:00-02:00" * Other timestamps are treated as being in the
     *         time zone configured in the Greenbyte Platform. Example: "2020-01-01T00:00:00" The
     *         end timestamp is **not** included in the time interval: for example, to select the
     *         full month of March 2020, set `timestampStart` to "2020-03-01T00:00:00" and
     *         `timestampEnd` to "2020-04-01T00:00:00". Timestamps selected in the portal will by
     *         default be in UTC.
     * @param  siteIds  Optional parameter: What sites to get alerts for.
     * @param  componentIds  Optional parameter: What components to get alerts for.
     * @param  status  Optional parameter: Which alert status to get alerts for.
     * @param  severity  Optional parameter: What severity of alerts to get: high severity or low
     *         severity. If not set, both high and low severity alerts are included.
     * @param  fields  Optional parameter: Which fields to include in the response. Valid fields are
     *         those defined in the `PredictAlert` schema (See Response Type). By default all fields
     *         are included.
     * @param  pageSize  Optional parameter: The number of items to return per page.
     * @param  page  Optional parameter: Which page to return when the number of items exceed the
     *         page size.
     * @param  useUtc  Optional parameter: Set to true to get timestamps in UTC.
     * @return    Returns the List of PredictAlertsResponse wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<List<PredictAlertsResponse>> getPredictAlerts(
            final List<Integer> deviceIds,
            final LocalDateTime timestampStart,
            final LocalDateTime timestampEnd,
            final List<Integer> siteIds,
            final List<Integer> componentIds,
            final PredictStatus status,
            final PredictSeverity severity,
            final List<String> fields,
            final Integer pageSize,
            final Integer page,
            final Boolean useUtc) throws ApiException, IOException {
        return prepareGetPredictAlertsRequest(deviceIds, timestampStart, timestampEnd, siteIds,
                componentIds, status, severity, fields, pageSize, page, useUtc).execute();
    }

    /**
     * Gets a list of Predict alerts based on filter criteria. The timestamps are in the time zone
     * configured in the Greenbyte Platform. Use the useUtc flag to get timestamps in UTC. _🔐 This
     * endpoint requires the **Predict** endpoint permission._ _This is a beta feature. Some details
     * might change before it is released as a stable version._.
     * @param  deviceIds  Required parameter: What devices to get alerts for.
     * @param  timestampStart  Required parameter: The beginning of the time interval to get data
     *         for (inclusive), in [RFC 3339, section
     *         5.6](https://tools.ietf.org/html/rfc3339#section-5.6) **date-time** format: *
     *         Timestamps ending with 'Z' are treated as UTC. Example: "2020-01-01T00:00:00Z" * Time
     *         zone (UTC) offset timestamps ending with '+HH:mm'/"-HH:mm" are also supported.
     *         Example: "2020-01-01T02:00:00-02:00" * Other timestamps are treated as being in the
     *         time zone configured in the Greenbyte Platform. Example: "2020-01-01T00:00:00" The
     *         start timestamp **is** included in the time interval: for example, to select the full
     *         month of March 2020, set `timestampStart` to "2020-03-01T00:00:00" and `timestampEnd`
     *         to "2020-04-01T00:00:00". Timestamps selected in the portal will by default be in
     *         UTC.
     * @param  timestampEnd  Required parameter: The end of the time interval to get data for
     *         (exclusive), in [RFC 3339, section
     *         5.6](https://tools.ietf.org/html/rfc3339#section-5.6) **date-time** format: *
     *         Timestamps ending with 'Z' are treated as UTC. Example: "2020-01-01T00:00:00Z" * Time
     *         zone (UTC) offset timestamps ending with '+HH:mm'/"-HH:mm" are also supported.
     *         Example: "2020-01-01T02:00:00-02:00" * Other timestamps are treated as being in the
     *         time zone configured in the Greenbyte Platform. Example: "2020-01-01T00:00:00" The
     *         end timestamp is **not** included in the time interval: for example, to select the
     *         full month of March 2020, set `timestampStart` to "2020-03-01T00:00:00" and
     *         `timestampEnd` to "2020-04-01T00:00:00". Timestamps selected in the portal will by
     *         default be in UTC.
     * @param  siteIds  Optional parameter: What sites to get alerts for.
     * @param  componentIds  Optional parameter: What components to get alerts for.
     * @param  status  Optional parameter: Which alert status to get alerts for.
     * @param  severity  Optional parameter: What severity of alerts to get: high severity or low
     *         severity. If not set, both high and low severity alerts are included.
     * @param  fields  Optional parameter: Which fields to include in the response. Valid fields are
     *         those defined in the `PredictAlert` schema (See Response Type). By default all fields
     *         are included.
     * @param  pageSize  Optional parameter: The number of items to return per page.
     * @param  page  Optional parameter: Which page to return when the number of items exceed the
     *         page size.
     * @param  useUtc  Optional parameter: Set to true to get timestamps in UTC.
     * @return    Returns the List of PredictAlertsResponse wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<List<PredictAlertsResponse>>> getPredictAlertsAsync(
            final List<Integer> deviceIds,
            final LocalDateTime timestampStart,
            final LocalDateTime timestampEnd,
            final List<Integer> siteIds,
            final List<Integer> componentIds,
            final PredictStatus status,
            final PredictSeverity severity,
            final List<String> fields,
            final Integer pageSize,
            final Integer page,
            final Boolean useUtc) {
        try {
            return prepareGetPredictAlertsRequest(deviceIds, timestampStart, timestampEnd, siteIds,
            componentIds, status, severity, fields, pageSize, page, useUtc).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getPredictAlerts.
     */
    private ApiCall<ApiResponse<List<PredictAlertsResponse>>, ApiException> prepareGetPredictAlertsRequest(
            final List<Integer> deviceIds,
            final LocalDateTime timestampStart,
            final LocalDateTime timestampEnd,
            final List<Integer> siteIds,
            final List<Integer> componentIds,
            final PredictStatus status,
            final PredictSeverity severity,
            final List<String> fields,
            final Integer pageSize,
            final Integer page,
            final Boolean useUtc) {
        return new ApiCall.Builder<ApiResponse<List<PredictAlertsResponse>>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/predict-alerts")
                        .queryParam(param -> param.key("deviceIds")
                                .value(deviceIds))
                        .queryParam(param -> param.key("timestampStart")
                                .value(DateTimeHelper.toRfc8601DateTime(timestampStart)))
                        .queryParam(param -> param.key("timestampEnd")
                                .value(DateTimeHelper.toRfc8601DateTime(timestampEnd)))
                        .queryParam(param -> param.key("siteIds")
                                .value(siteIds).isRequired(false))
                        .queryParam(param -> param.key("componentIds")
                                .value(componentIds).isRequired(false))
                        .queryParam(param -> param.key("status")
                                .value((status != null) ? status.value() : null).isRequired(false))
                        .queryParam(param -> param.key("severity")
                                .value((severity != null) ? severity.value() : null).isRequired(false))
                        .queryParam(param -> param.key("fields")
                                .value(fields).isRequired(false))
                        .queryParam(param -> param.key("pageSize")
                                .value((pageSize != null) ? pageSize : 50).isRequired(false))
                        .queryParam(param -> param.key("page")
                                .value((page != null) ? page : 1).isRequired(false))
                        .queryParam(param -> param.key("useUtc")
                                .value((useUtc != null) ? useUtc : false).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("ApiKeyHeaderAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserializeArray(response,
                                        PredictAlertsResponse[].class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The request cannot be fulfilled due to bad syntax.",
                                (reason, context) -> new PredictAlerts400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request is missing a valid API key.",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("One of the following:\n* The API key does not authorize access to the requested endpoint because of a missing endpoint permission.\n* The API key does not authorize access to the requested data. Devices, sites or data signals can be limited.",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("405",
                                 ErrorCase.setReason("The HTTP method is not allowed for the endpoint.",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("429",
                                 ErrorCase.setReason("The API key has been used in too many requests in a given amount\nof time. The following headers will be set in the response:\n* `X-Rate-Limit-Limit` – The rate limit period (for example\n  \"1m\", \"12h\", or \"1d\").\n* `X-Rate-Limit-Remaining` – The remaining number of requests\n  for this period.\n* `X-Rate-Limit-Reset` – The UTC timestamp string (in ISO 8601\n  format) when the remaining number of requests resets.\n\nThe limit is currently 1,000 requests/minute per API key and IP\naddress.",
                                (reason, context) -> new PredictAlerts429ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}