/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.apis;

import cloud.greenbyte.intro.ApiHelper;
import cloud.greenbyte.intro.DateTimeHelper;
import cloud.greenbyte.intro.Server;
import cloud.greenbyte.intro.exceptions.Activestatus400ErrorException;
import cloud.greenbyte.intro.exceptions.Activestatus429ErrorException;
import cloud.greenbyte.intro.exceptions.ApiException;
import cloud.greenbyte.intro.exceptions.Status400ErrorException;
import cloud.greenbyte.intro.exceptions.Status429ErrorException;
import cloud.greenbyte.intro.http.request.HttpMethod;
import cloud.greenbyte.intro.http.response.ApiResponse;
import cloud.greenbyte.intro.models.ContractType1;
import cloud.greenbyte.intro.models.StatusCategory;
import cloud.greenbyte.intro.models.StatusItem;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class StatusesApi extends BaseApi {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public StatusesApi(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Gets statuses for multiple devices during the given time period. The timestamps are in the
     * time zone configured in the Greenbyte Platform. Use the useUtc flag to get timestamps in UTC.
     * _🔐 This endpoint requires the **Statuses** endpoint permission._ _This request can also be
     * made using the POST method, with a request to `status.json` and a JSON request body instead
     * of query parameters._.
     * @param  deviceIds  Required parameter: Which devices to get statuses for.
     * @param  timestampStart  Required parameter: The beginning of the time interval to get data
     *         for (inclusive), in [RFC 3339, section
     *         5.6](https://tools.ietf.org/html/rfc3339#section-5.6) **date-time** format: *
     *         Timestamps ending with 'Z' are treated as UTC. Example: "2020-01-01T00:00:00Z" * Time
     *         zone (UTC) offset timestamps ending with '+HH:mm'/"-HH:mm" are also supported.
     *         Example: "2020-01-01T02:00:00-02:00" * Other timestamps are treated as being in the
     *         time zone configured in the Greenbyte Platform. Example: "2020-01-01T00:00:00" The
     *         start timestamp **is** included in the time interval: for example, to select the full
     *         month of March 2020, set `timestampStart` to "2020-03-01T00:00:00" and `timestampEnd`
     *         to "2020-04-01T00:00:00". Timestamps selected in the portal will by default be in
     *         UTC.
     * @param  timestampEnd  Required parameter: The end of the time interval to get data for
     *         (exclusive), in [RFC 3339, section
     *         5.6](https://tools.ietf.org/html/rfc3339#section-5.6) **date-time** format: *
     *         Timestamps ending with 'Z' are treated as UTC. Example: "2020-01-01T00:00:00Z" * Time
     *         zone (UTC) offset timestamps ending with '+HH:mm'/"-HH:mm" are also supported.
     *         Example: "2020-01-01T02:00:00-02:00" * Other timestamps are treated as being in the
     *         time zone configured in the Greenbyte Platform. Example: "2020-01-01T00:00:00" The
     *         end timestamp is **not** included in the time interval: for example, to select the
     *         full month of March 2020, set `timestampStart` to "2020-03-01T00:00:00" and
     *         `timestampEnd` to "2020-04-01T00:00:00". Timestamps selected in the portal will by
     *         default be in UTC.
     * @param  category  Optional parameter: Which status categories to get statuses for.
     * @param  lostProductionSignalId  Optional parameter: Which data signal to use for calculating
     *         lost production. Defaults to the configured default lost production signal.
     * @param  fields  Optional parameter: Which fields to include in the response. Valid fields are
     *         those defined in the `StatusItem` schema (See Response Type). By default all fields
     *         are included.
     * @param  sortBy  Optional parameter: Which fields to sort the response items by.
     * @param  sortAsc  Optional parameter: Whether to sort the items in ascending order.
     * @param  pageSize  Optional parameter: The number of items to return per page.
     * @param  page  Optional parameter: Which page to return when the number of items exceed the
     *         page size.
     * @param  useUtc  Optional parameter: Set to true to get timestamps in UTC.
     * @param  contractType  Optional parameter: Which contract type to use if using multiple
     *         availability contracts.
     * @return    Returns the List of StatusItem wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<List<StatusItem>> getStatuses(
            final List<Integer> deviceIds,
            final LocalDateTime timestampStart,
            final LocalDateTime timestampEnd,
            final List<StatusCategory> category,
            final Integer lostProductionSignalId,
            final List<String> fields,
            final List<String> sortBy,
            final Boolean sortAsc,
            final Integer pageSize,
            final Integer page,
            final Boolean useUtc,
            final ContractType1 contractType) throws ApiException, IOException {
        return prepareGetStatusesRequest(deviceIds, timestampStart, timestampEnd, category,
                lostProductionSignalId, fields, sortBy, sortAsc, pageSize, page, useUtc,
                contractType).execute();
    }

    /**
     * Gets statuses for multiple devices during the given time period. The timestamps are in the
     * time zone configured in the Greenbyte Platform. Use the useUtc flag to get timestamps in UTC.
     * _🔐 This endpoint requires the **Statuses** endpoint permission._ _This request can also be
     * made using the POST method, with a request to `status.json` and a JSON request body instead
     * of query parameters._.
     * @param  deviceIds  Required parameter: Which devices to get statuses for.
     * @param  timestampStart  Required parameter: The beginning of the time interval to get data
     *         for (inclusive), in [RFC 3339, section
     *         5.6](https://tools.ietf.org/html/rfc3339#section-5.6) **date-time** format: *
     *         Timestamps ending with 'Z' are treated as UTC. Example: "2020-01-01T00:00:00Z" * Time
     *         zone (UTC) offset timestamps ending with '+HH:mm'/"-HH:mm" are also supported.
     *         Example: "2020-01-01T02:00:00-02:00" * Other timestamps are treated as being in the
     *         time zone configured in the Greenbyte Platform. Example: "2020-01-01T00:00:00" The
     *         start timestamp **is** included in the time interval: for example, to select the full
     *         month of March 2020, set `timestampStart` to "2020-03-01T00:00:00" and `timestampEnd`
     *         to "2020-04-01T00:00:00". Timestamps selected in the portal will by default be in
     *         UTC.
     * @param  timestampEnd  Required parameter: The end of the time interval to get data for
     *         (exclusive), in [RFC 3339, section
     *         5.6](https://tools.ietf.org/html/rfc3339#section-5.6) **date-time** format: *
     *         Timestamps ending with 'Z' are treated as UTC. Example: "2020-01-01T00:00:00Z" * Time
     *         zone (UTC) offset timestamps ending with '+HH:mm'/"-HH:mm" are also supported.
     *         Example: "2020-01-01T02:00:00-02:00" * Other timestamps are treated as being in the
     *         time zone configured in the Greenbyte Platform. Example: "2020-01-01T00:00:00" The
     *         end timestamp is **not** included in the time interval: for example, to select the
     *         full month of March 2020, set `timestampStart` to "2020-03-01T00:00:00" and
     *         `timestampEnd` to "2020-04-01T00:00:00". Timestamps selected in the portal will by
     *         default be in UTC.
     * @param  category  Optional parameter: Which status categories to get statuses for.
     * @param  lostProductionSignalId  Optional parameter: Which data signal to use for calculating
     *         lost production. Defaults to the configured default lost production signal.
     * @param  fields  Optional parameter: Which fields to include in the response. Valid fields are
     *         those defined in the `StatusItem` schema (See Response Type). By default all fields
     *         are included.
     * @param  sortBy  Optional parameter: Which fields to sort the response items by.
     * @param  sortAsc  Optional parameter: Whether to sort the items in ascending order.
     * @param  pageSize  Optional parameter: The number of items to return per page.
     * @param  page  Optional parameter: Which page to return when the number of items exceed the
     *         page size.
     * @param  useUtc  Optional parameter: Set to true to get timestamps in UTC.
     * @param  contractType  Optional parameter: Which contract type to use if using multiple
     *         availability contracts.
     * @return    Returns the List of StatusItem wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<List<StatusItem>>> getStatusesAsync(
            final List<Integer> deviceIds,
            final LocalDateTime timestampStart,
            final LocalDateTime timestampEnd,
            final List<StatusCategory> category,
            final Integer lostProductionSignalId,
            final List<String> fields,
            final List<String> sortBy,
            final Boolean sortAsc,
            final Integer pageSize,
            final Integer page,
            final Boolean useUtc,
            final ContractType1 contractType) {
        try {
            return prepareGetStatusesRequest(deviceIds, timestampStart, timestampEnd, category,
            lostProductionSignalId, fields, sortBy, sortAsc, pageSize, page, useUtc,
            contractType).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getStatuses.
     */
    private ApiCall<ApiResponse<List<StatusItem>>, ApiException> prepareGetStatusesRequest(
            final List<Integer> deviceIds,
            final LocalDateTime timestampStart,
            final LocalDateTime timestampEnd,
            final List<StatusCategory> category,
            final Integer lostProductionSignalId,
            final List<String> fields,
            final List<String> sortBy,
            final Boolean sortAsc,
            final Integer pageSize,
            final Integer page,
            final Boolean useUtc,
            final ContractType1 contractType) {
        return new ApiCall.Builder<ApiResponse<List<StatusItem>>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/status")
                        .queryParam(param -> param.key("deviceIds")
                                .value(deviceIds))
                        .queryParam(param -> param.key("timestampStart")
                                .value(DateTimeHelper.toRfc8601DateTime(timestampStart)))
                        .queryParam(param -> param.key("timestampEnd")
                                .value(DateTimeHelper.toRfc8601DateTime(timestampEnd)))
                        .queryParam(param -> param.key("category")
                                .value(StatusCategory.toValue(category)).isRequired(false))
                        .queryParam(param -> param.key("lostProductionSignalId")
                                .value(lostProductionSignalId).isRequired(false))
                        .queryParam(param -> param.key("fields")
                                .value(fields).isRequired(false))
                        .queryParam(param -> param.key("sortBy")
                                .value(sortBy).isRequired(false))
                        .queryParam(param -> param.key("sortAsc")
                                .value((sortAsc != null) ? sortAsc : false).isRequired(false))
                        .queryParam(param -> param.key("pageSize")
                                .value((pageSize != null) ? pageSize : 50).isRequired(false))
                        .queryParam(param -> param.key("page")
                                .value((page != null) ? page : 1).isRequired(false))
                        .queryParam(param -> param.key("useUtc")
                                .value((useUtc != null) ? useUtc : false).isRequired(false))
                        .queryParam(param -> param.key("contractType")
                                .value((contractType != null) ? contractType.value() : null).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("ApiKeyHeaderAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserializeArray(response,
                                        StatusItem[].class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The request cannot be fulfilled due to bad syntax.",
                                (reason, context) -> new Status400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request is missing a valid API key.",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("One of the following:\n* The API key does not authorize access to the requested endpoint because of a missing endpoint permission.\n* The API key does not authorize access to the requested data. Devices, sites or data signals can be limited.",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("405",
                                 ErrorCase.setReason("The HTTP method is not allowed for the endpoint.",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("429",
                                 ErrorCase.setReason("The API key has been used in too many requests in a given amount\nof time. The following headers will be set in the response:\n* `X-Rate-Limit-Limit` – The rate limit period (for example\n  \"1m\", \"12h\", or \"1d\").\n* `X-Rate-Limit-Remaining` – The remaining number of requests\n  for this period.\n* `X-Rate-Limit-Reset` – The UTC timestamp string (in ISO 8601\n  format) when the remaining number of requests resets.\n\nThe limit is currently 1,000 requests/minute per API key and IP\naddress.",
                                (reason, context) -> new Status429ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Gets active statuses for multiple devices. The timestamps are in the time zone configured in
     * the Greenbyte Platform. Use the useUtc flag to get timestamps in UTC. _🔐 This endpoint
     * requires the **Statuses** endpoint permission._ _This request can also be made using the POST
     * method, with a request to `activestatus.json` and a JSON request body instead of query
     * parameters._.
     * @param  deviceIds  Required parameter: Which devices to get statuses for.
     * @param  category  Optional parameter: Which status categories to get statuses for.
     * @param  lostProductionSignalId  Optional parameter: Which data signal to use for calculating
     *         lost production. Defaults to the configured default lost production signal.
     * @param  fields  Optional parameter: Which fields to include in the response. Valid fields are
     *         those defined in the `StatusItem` schema (See Response Type). By default all fields
     *         are included.
     * @param  sortBy  Optional parameter: Which fields to sort the response items by.
     * @param  sortAsc  Optional parameter: Whether to sort the items in ascending order.
     * @param  pageSize  Optional parameter: The number of items to return per page.
     * @param  page  Optional parameter: Which page to return when the number of items exceed the
     *         page size.
     * @param  useUtc  Optional parameter: Set to true to get timestamps in UTC.
     * @param  contractType  Optional parameter: Which contract type to use if using multiple
     *         availability contracts.
     * @return    Returns the List of StatusItem wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<List<StatusItem>> getActiveStatuses(
            final List<Integer> deviceIds,
            final List<StatusCategory> category,
            final Integer lostProductionSignalId,
            final List<String> fields,
            final List<String> sortBy,
            final Boolean sortAsc,
            final Integer pageSize,
            final Integer page,
            final Boolean useUtc,
            final ContractType1 contractType) throws ApiException, IOException {
        return prepareGetActiveStatusesRequest(deviceIds, category, lostProductionSignalId, fields,
                sortBy, sortAsc, pageSize, page, useUtc, contractType).execute();
    }

    /**
     * Gets active statuses for multiple devices. The timestamps are in the time zone configured in
     * the Greenbyte Platform. Use the useUtc flag to get timestamps in UTC. _🔐 This endpoint
     * requires the **Statuses** endpoint permission._ _This request can also be made using the POST
     * method, with a request to `activestatus.json` and a JSON request body instead of query
     * parameters._.
     * @param  deviceIds  Required parameter: Which devices to get statuses for.
     * @param  category  Optional parameter: Which status categories to get statuses for.
     * @param  lostProductionSignalId  Optional parameter: Which data signal to use for calculating
     *         lost production. Defaults to the configured default lost production signal.
     * @param  fields  Optional parameter: Which fields to include in the response. Valid fields are
     *         those defined in the `StatusItem` schema (See Response Type). By default all fields
     *         are included.
     * @param  sortBy  Optional parameter: Which fields to sort the response items by.
     * @param  sortAsc  Optional parameter: Whether to sort the items in ascending order.
     * @param  pageSize  Optional parameter: The number of items to return per page.
     * @param  page  Optional parameter: Which page to return when the number of items exceed the
     *         page size.
     * @param  useUtc  Optional parameter: Set to true to get timestamps in UTC.
     * @param  contractType  Optional parameter: Which contract type to use if using multiple
     *         availability contracts.
     * @return    Returns the List of StatusItem wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<List<StatusItem>>> getActiveStatusesAsync(
            final List<Integer> deviceIds,
            final List<StatusCategory> category,
            final Integer lostProductionSignalId,
            final List<String> fields,
            final List<String> sortBy,
            final Boolean sortAsc,
            final Integer pageSize,
            final Integer page,
            final Boolean useUtc,
            final ContractType1 contractType) {
        try {
            return prepareGetActiveStatusesRequest(deviceIds, category, lostProductionSignalId, fields,
            sortBy, sortAsc, pageSize, page, useUtc, contractType).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getActiveStatuses.
     */
    private ApiCall<ApiResponse<List<StatusItem>>, ApiException> prepareGetActiveStatusesRequest(
            final List<Integer> deviceIds,
            final List<StatusCategory> category,
            final Integer lostProductionSignalId,
            final List<String> fields,
            final List<String> sortBy,
            final Boolean sortAsc,
            final Integer pageSize,
            final Integer page,
            final Boolean useUtc,
            final ContractType1 contractType) {
        return new ApiCall.Builder<ApiResponse<List<StatusItem>>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/activestatus")
                        .queryParam(param -> param.key("deviceIds")
                                .value(deviceIds))
                        .queryParam(param -> param.key("category")
                                .value(StatusCategory.toValue(category)).isRequired(false))
                        .queryParam(param -> param.key("lostProductionSignalId")
                                .value(lostProductionSignalId).isRequired(false))
                        .queryParam(param -> param.key("fields")
                                .value(fields).isRequired(false))
                        .queryParam(param -> param.key("sortBy")
                                .value(sortBy).isRequired(false))
                        .queryParam(param -> param.key("sortAsc")
                                .value((sortAsc != null) ? sortAsc : false).isRequired(false))
                        .queryParam(param -> param.key("pageSize")
                                .value((pageSize != null) ? pageSize : 50).isRequired(false))
                        .queryParam(param -> param.key("page")
                                .value((page != null) ? page : 1).isRequired(false))
                        .queryParam(param -> param.key("useUtc")
                                .value((useUtc != null) ? useUtc : false).isRequired(false))
                        .queryParam(param -> param.key("contractType")
                                .value((contractType != null) ? contractType.value() : null).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("ApiKeyHeaderAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserializeArray(response,
                                        StatusItem[].class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("The request cannot be fulfilled due to bad syntax.",
                                (reason, context) -> new Activestatus400ErrorException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("The request is missing a valid API key.",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("One of the following:\n* The API key does not authorize access to the requested endpoint because of a missing endpoint permission.\n* The API key does not authorize access to the requested data. Devices, sites or data signals can be limited.",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("405",
                                 ErrorCase.setReason("The HTTP method is not allowed for the endpoint.",
                                (reason, context) -> new ApiException(reason, context)))
                        .localErrorCase("429",
                                 ErrorCase.setReason("The API key has been used in too many requests in a given amount\nof time. The following headers will be set in the response:\n* `X-Rate-Limit-Limit` – The rate limit period (for example\n  \"1m\", \"12h\", or \"1d\").\n* `X-Rate-Limit-Remaining` – The remaining number of requests\n  for this period.\n* `X-Rate-Limit-Reset` – The UTC timestamp string (in ISO 8601\n  format) when the remaining number of requests resets.\n\nThe limit is currently 1,000 requests/minute per API key and IP\naddress.",
                                (reason, context) -> new Activestatus429ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}