/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * AggregateMode to be used.
 */
public enum AggregateMode {
    DEVICE,

    DEVICELEVEL,

    SITE,

    PORTFOLIO,

    SITELEVEL;

    private static TreeMap<String, AggregateMode> valueMap = new TreeMap<>();
    private String value;

    static {
        DEVICE.value = "device";
        DEVICELEVEL.value = "deviceLevel";
        SITE.value = "site";
        PORTFOLIO.value = "portfolio";
        SITELEVEL.value = "siteLevel";

        valueMap.put("device", DEVICE);
        valueMap.put("deviceLevel", DEVICELEVEL);
        valueMap.put("site", SITE);
        valueMap.put("portfolio", PORTFOLIO);
        valueMap.put("siteLevel", SITELEVEL);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AggregateMode constructFromString(String toConvert) throws IOException {
        AggregateMode enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AggregateMode fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AggregateMode values to list of string values.
     * @param toConvert The list of AggregateMode values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AggregateMode> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AggregateMode enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 