/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import cloud.greenbyte.intro.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for AlertItem type.
 */
public class AlertItem {
    private Integer deviceId;
    private Integer ruleId;
    private LocalDateTime timestampStart;
    private LocalDateTime timestampEnd;
    private String message;
    private String comment;
    private String description;
    private String details;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public AlertItem() {
    }

    /**
     * Initialization constructor.
     * @param  deviceId  Integer value for deviceId.
     * @param  ruleId  Integer value for ruleId.
     * @param  timestampStart  LocalDateTime value for timestampStart.
     * @param  timestampEnd  LocalDateTime value for timestampEnd.
     * @param  message  String value for message.
     * @param  comment  String value for comment.
     * @param  description  String value for description.
     * @param  details  String value for details.
     */
    public AlertItem(
            Integer deviceId,
            Integer ruleId,
            LocalDateTime timestampStart,
            LocalDateTime timestampEnd,
            String message,
            String comment,
            String description,
            String details) {
        this.deviceId = deviceId;
        this.ruleId = ruleId;
        this.timestampStart = timestampStart;
        this.timestampEnd = timestampEnd;
        this.message = message;
        this.comment = comment;
        this.description = description;
        this.details = details;
    }

    /**
     * Getter for DeviceId.
     * The id of the device the alert was generated for.
     * @return Returns the Integer
     */
    @JsonGetter("deviceId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * Setter for DeviceId.
     * The id of the device the alert was generated for.
     * @param deviceId Value for Integer
     */
    @JsonSetter("deviceId")
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Getter for RuleId.
     * The id of the rule the alert is based on.
     * @return Returns the Integer
     */
    @JsonGetter("ruleId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * Setter for RuleId.
     * The id of the rule the alert is based on.
     * @param ruleId Value for Integer
     */
    @JsonSetter("ruleId")
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * Getter for TimestampStart.
     * The timestamp when the alert began. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestampStart")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestampStart() {
        return timestampStart;
    }

    /**
     * Setter for TimestampStart.
     * The timestamp when the alert began. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @param timestampStart Value for LocalDateTime
     */
    @JsonSetter("timestampStart")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestampStart(LocalDateTime timestampStart) {
        this.timestampStart = timestampStart;
    }

    /**
     * Getter for TimestampEnd.
     * The timestamp when the alert ended. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestampEnd")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestampEnd() {
        return timestampEnd;
    }

    /**
     * Setter for TimestampEnd.
     * The timestamp when the alert ended. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @param timestampEnd Value for LocalDateTime
     */
    @JsonSetter("timestampEnd")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestampEnd(LocalDateTime timestampEnd) {
        this.timestampEnd = timestampEnd;
    }

    /**
     * Getter for Message.
     * The title of the rule the alert is based on.
     * @return Returns the String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * The title of the rule the alert is based on.
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for Comment.
     * A user comment associated with the alert.
     * @return Returns the String
     */
    @JsonGetter("comment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getComment() {
        return comment;
    }

    /**
     * Setter for Comment.
     * A user comment associated with the alert.
     * @param comment Value for String
     */
    @JsonSetter("comment")
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for Description.
     * A description explaning the rule the alert is based on.
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * A description explaning the rule the alert is based on.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Details.
     * Additional details for the alert. Note that the structure of this data is subject to change.
     * @return Returns the String
     */
    @JsonGetter("details")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDetails() {
        return details;
    }

    /**
     * Setter for Details.
     * Additional details for the alert. Note that the structure of this data is subject to change.
     * @param details Value for String
     */
    @JsonSetter("details")
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this AlertItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AlertItem [" + "deviceId=" + deviceId + ", ruleId=" + ruleId + ", timestampStart="
                + timestampStart + ", timestampEnd=" + timestampEnd + ", message=" + message
                + ", comment=" + comment + ", description=" + description + ", details=" + details
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link AlertItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AlertItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .deviceId(getDeviceId())
                .ruleId(getRuleId())
                .timestampStart(getTimestampStart())
                .timestampEnd(getTimestampEnd())
                .message(getMessage())
                .comment(getComment())
                .description(getDescription())
                .details(getDetails());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link AlertItem}.
     */
    public static class Builder {
        private Integer deviceId;
        private Integer ruleId;
        private LocalDateTime timestampStart;
        private LocalDateTime timestampEnd;
        private String message;
        private String comment;
        private String description;
        private String details;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for deviceId.
         * @param  deviceId  Integer value for deviceId.
         * @return Builder
         */
        public Builder deviceId(Integer deviceId) {
            this.deviceId = deviceId;
            return this;
        }

        /**
         * Setter for ruleId.
         * @param  ruleId  Integer value for ruleId.
         * @return Builder
         */
        public Builder ruleId(Integer ruleId) {
            this.ruleId = ruleId;
            return this;
        }

        /**
         * Setter for timestampStart.
         * @param  timestampStart  LocalDateTime value for timestampStart.
         * @return Builder
         */
        public Builder timestampStart(LocalDateTime timestampStart) {
            this.timestampStart = timestampStart;
            return this;
        }

        /**
         * Setter for timestampEnd.
         * @param  timestampEnd  LocalDateTime value for timestampEnd.
         * @return Builder
         */
        public Builder timestampEnd(LocalDateTime timestampEnd) {
            this.timestampEnd = timestampEnd;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for comment.
         * @param  comment  String value for comment.
         * @return Builder
         */
        public Builder comment(String comment) {
            this.comment = comment;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for details.
         * @param  details  String value for details.
         * @return Builder
         */
        public Builder details(String details) {
            this.details = details;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link AlertItem} object using the set fields.
         * @return {@link AlertItem}
         */
        public AlertItem build() {
            AlertItem model =
                    new AlertItem(deviceId, ruleId, timestampStart, timestampEnd, message, comment,
                            description, details);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
