/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ClientConfiguration type.
 */
public class ClientConfiguration {
    private String title;
    private String tag;
    private String urlWeb;
    private String urlApi;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ClientConfiguration() {
    }

    /**
     * Initialization constructor.
     * @param  title  String value for title.
     * @param  tag  String value for tag.
     * @param  urlWeb  String value for urlWeb.
     * @param  urlApi  String value for urlApi.
     */
    public ClientConfiguration(
            String title,
            String tag,
            String urlWeb,
            String urlApi) {
        this.title = title;
        this.tag = tag;
        this.urlWeb = urlWeb;
        this.urlApi = urlApi;
    }

    /**
     * Getter for Title.
     * The title of your Greenbyte Platform website.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * The title of your Greenbyte Platform website.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for Tag.
     * Your internal customer tag.
     * @return Returns the String
     */
    @JsonGetter("tag")
    public String getTag() {
        return tag;
    }

    /**
     * Setter for Tag.
     * Your internal customer tag.
     * @param tag Value for String
     */
    @JsonSetter("tag")
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * Getter for UrlWeb.
     * Your URL to access the Greenbyte Platform website.
     * @return Returns the String
     */
    @JsonGetter("urlWeb")
    public String getUrlWeb() {
        return urlWeb;
    }

    /**
     * Setter for UrlWeb.
     * Your URL to access the Greenbyte Platform website.
     * @param urlWeb Value for String
     */
    @JsonSetter("urlWeb")
    public void setUrlWeb(String urlWeb) {
        this.urlWeb = urlWeb;
    }

    /**
     * Getter for UrlApi.
     * Your URL to access the Greenbyte Platform API.
     * @return Returns the String
     */
    @JsonGetter("urlApi")
    public String getUrlApi() {
        return urlApi;
    }

    /**
     * Setter for UrlApi.
     * Your URL to access the Greenbyte Platform API.
     * @param urlApi Value for String
     */
    @JsonSetter("urlApi")
    public void setUrlApi(String urlApi) {
        this.urlApi = urlApi;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ClientConfiguration into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ClientConfiguration [" + "title=" + title + ", tag=" + tag + ", urlWeb=" + urlWeb
                + ", urlApi=" + urlApi + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ClientConfiguration.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ClientConfiguration.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(title, tag, urlWeb, urlApi);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ClientConfiguration}.
     */
    public static class Builder {
        private String title;
        private String tag;
        private String urlWeb;
        private String urlApi;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  title  String value for title.
         * @param  tag  String value for tag.
         * @param  urlWeb  String value for urlWeb.
         * @param  urlApi  String value for urlApi.
         */
        public Builder(String title, String tag, String urlWeb, String urlApi) {
            this.title = title;
            this.tag = tag;
            this.urlWeb = urlWeb;
            this.urlApi = urlApi;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for tag.
         * @param  tag  String value for tag.
         * @return Builder
         */
        public Builder tag(String tag) {
            this.tag = tag;
            return this;
        }

        /**
         * Setter for urlWeb.
         * @param  urlWeb  String value for urlWeb.
         * @return Builder
         */
        public Builder urlWeb(String urlWeb) {
            this.urlWeb = urlWeb;
            return this;
        }

        /**
         * Setter for urlApi.
         * @param  urlApi  String value for urlApi.
         * @return Builder
         */
        public Builder urlApi(String urlApi) {
            this.urlApi = urlApi;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ClientConfiguration} object using the set fields.
         * @return {@link ClientConfiguration}
         */
        public ClientConfiguration build() {
            ClientConfiguration model =
                    new ClientConfiguration(title, tag, urlWeb, urlApi);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
