/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ComponentAlert type.
 */
public class ComponentAlert {
    private Integer componentId;
    private String componentName;
    private String componentTag;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ComponentAlert() {
    }

    /**
     * Initialization constructor.
     * @param  componentId  Integer value for componentId.
     * @param  componentName  String value for componentName.
     * @param  componentTag  String value for componentTag.
     */
    public ComponentAlert(
            Integer componentId,
            String componentName,
            String componentTag) {
        this.componentId = componentId;
        this.componentName = componentName;
        this.componentTag = componentTag;
    }

    /**
     * Getter for ComponentId.
     * @return Returns the Integer
     */
    @JsonGetter("componentId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getComponentId() {
        return componentId;
    }

    /**
     * Setter for ComponentId.
     * @param componentId Value for Integer
     */
    @JsonSetter("componentId")
    public void setComponentId(Integer componentId) {
        this.componentId = componentId;
    }

    /**
     * Getter for ComponentName.
     * The name of the component.
     * @return Returns the String
     */
    @JsonGetter("componentName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getComponentName() {
        return componentName;
    }

    /**
     * Setter for ComponentName.
     * The name of the component.
     * @param componentName Value for String
     */
    @JsonSetter("componentName")
    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }

    /**
     * Getter for ComponentTag.
     * The component tag.
     * @return Returns the String
     */
    @JsonGetter("componentTag")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getComponentTag() {
        return componentTag;
    }

    /**
     * Setter for ComponentTag.
     * The component tag.
     * @param componentTag Value for String
     */
    @JsonSetter("componentTag")
    public void setComponentTag(String componentTag) {
        this.componentTag = componentTag;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ComponentAlert into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ComponentAlert [" + "componentId=" + componentId + ", componentName="
                + componentName + ", componentTag=" + componentTag + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ComponentAlert.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ComponentAlert.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .componentId(getComponentId())
                .componentName(getComponentName())
                .componentTag(getComponentTag());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ComponentAlert}.
     */
    public static class Builder {
        private Integer componentId;
        private String componentName;
        private String componentTag;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for componentId.
         * @param  componentId  Integer value for componentId.
         * @return Builder
         */
        public Builder componentId(Integer componentId) {
            this.componentId = componentId;
            return this;
        }

        /**
         * Setter for componentName.
         * @param  componentName  String value for componentName.
         * @return Builder
         */
        public Builder componentName(String componentName) {
            this.componentName = componentName;
            return this;
        }

        /**
         * Setter for componentTag.
         * @param  componentTag  String value for componentTag.
         * @return Builder
         */
        public Builder componentTag(String componentTag) {
            this.componentTag = componentTag;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ComponentAlert} object using the set fields.
         * @return {@link ComponentAlert}
         */
        public ComponentAlert build() {
            ComponentAlert model =
                    new ComponentAlert(componentId, componentName, componentTag);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
