/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ConfigurationItem type.
 */
public class ConfigurationItem {
    private Client client;
    private TimeZone timeZone;
    private DataSignals dataSignals;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ConfigurationItem() {
    }

    /**
     * Initialization constructor.
     * @param  client  Client value for client.
     * @param  timeZone  TimeZone value for timeZone.
     * @param  dataSignals  DataSignals value for dataSignals.
     */
    public ConfigurationItem(
            Client client,
            TimeZone timeZone,
            DataSignals dataSignals) {
        this.client = client;
        this.timeZone = timeZone;
        this.dataSignals = dataSignals;
    }

    /**
     * Getter for Client.
     * @return Returns the Client
     */
    @JsonGetter("client")
    public Client getClient() {
        return client;
    }

    /**
     * Setter for Client.
     * @param client Value for Client
     */
    @JsonSetter("client")
    public void setClient(Client client) {
        this.client = client;
    }

    /**
     * Getter for TimeZone.
     * @return Returns the TimeZone
     */
    @JsonGetter("timeZone")
    public TimeZone getTimeZone() {
        return timeZone;
    }

    /**
     * Setter for TimeZone.
     * @param timeZone Value for TimeZone
     */
    @JsonSetter("timeZone")
    public void setTimeZone(TimeZone timeZone) {
        this.timeZone = timeZone;
    }

    /**
     * Getter for DataSignals.
     * @return Returns the DataSignals
     */
    @JsonGetter("dataSignals")
    public DataSignals getDataSignals() {
        return dataSignals;
    }

    /**
     * Setter for DataSignals.
     * @param dataSignals Value for DataSignals
     */
    @JsonSetter("dataSignals")
    public void setDataSignals(DataSignals dataSignals) {
        this.dataSignals = dataSignals;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ConfigurationItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ConfigurationItem [" + "client=" + client + ", timeZone=" + timeZone
                + ", dataSignals=" + dataSignals + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link ConfigurationItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ConfigurationItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(client, timeZone, dataSignals);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ConfigurationItem}.
     */
    public static class Builder {
        private Client client;
        private TimeZone timeZone;
        private DataSignals dataSignals;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  client  Client value for client.
         * @param  timeZone  TimeZone value for timeZone.
         * @param  dataSignals  DataSignals value for dataSignals.
         */
        public Builder(Client client, TimeZone timeZone, DataSignals dataSignals) {
            this.client = client;
            this.timeZone = timeZone;
            this.dataSignals = dataSignals;
        }

        /**
         * Setter for client.
         * @param  client  Client value for client.
         * @return Builder
         */
        public Builder client(Client client) {
            this.client = client;
            return this;
        }

        /**
         * Setter for timeZone.
         * @param  timeZone  TimeZone value for timeZone.
         * @return Builder
         */
        public Builder timeZone(TimeZone timeZone) {
            this.timeZone = timeZone;
            return this;
        }

        /**
         * Setter for dataSignals.
         * @param  dataSignals  DataSignals value for dataSignals.
         * @return Builder
         */
        public Builder dataSignals(DataSignals dataSignals) {
            this.dataSignals = dataSignals;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ConfigurationItem} object using the set fields.
         * @return {@link ConfigurationItem}
         */
        public ConfigurationItem build() {
            ConfigurationItem model =
                    new ConfigurationItem(client, timeZone, dataSignals);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
