/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for DataRealTimeItem type.
 */
public class DataRealTimeItem {
    private AggregateMode aggregate;
    private int aggregateId;
    private List<String> aggregatePathNames;
    private List<Integer> deviceIds;
    private CalculationModeRealTime calculation;
    private DataSignal1 dataSignal;
    private Map<String, Double> data;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DataRealTimeItem() {
    }

    /**
     * Initialization constructor.
     * @param  aggregate  AggregateMode value for aggregate.
     * @param  aggregateId  int value for aggregateId.
     * @param  deviceIds  List of Integer value for deviceIds.
     * @param  calculation  CalculationModeRealTime value for calculation.
     * @param  dataSignal  DataSignal1 value for dataSignal.
     * @param  data  Map of String, value for data.
     * @param  aggregatePathNames  List of String value for aggregatePathNames.
     */
    public DataRealTimeItem(
            AggregateMode aggregate,
            int aggregateId,
            List<Integer> deviceIds,
            CalculationModeRealTime calculation,
            DataSignal1 dataSignal,
            Map<String, Double> data,
            List<String> aggregatePathNames) {
        this.aggregate = aggregate;
        this.aggregateId = aggregateId;
        this.aggregatePathNames = aggregatePathNames;
        this.deviceIds = deviceIds;
        this.calculation = calculation;
        this.dataSignal = dataSignal;
        this.data = data;
    }

    /**
     * Getter for Aggregate.
     * @return Returns the AggregateMode
     */
    @JsonGetter("aggregate")
    public AggregateMode getAggregate() {
        return aggregate;
    }

    /**
     * Setter for Aggregate.
     * @param aggregate Value for AggregateMode
     */
    @JsonSetter("aggregate")
    public void setAggregate(AggregateMode aggregate) {
        this.aggregate = aggregate;
    }

    /**
     * Getter for AggregateId.
     * The id of this aggregate group: device id, site id, or the constant -1 for portfolio. For
     * `siteLevel` aggregation a generated unique id is used.
     * @return Returns the int
     */
    @JsonGetter("aggregateId")
    public int getAggregateId() {
        return aggregateId;
    }

    /**
     * Setter for AggregateId.
     * The id of this aggregate group: device id, site id, or the constant -1 for portfolio. For
     * `siteLevel` aggregation a generated unique id is used.
     * @param aggregateId Value for int
     */
    @JsonSetter("aggregateId")
    public void setAggregateId(int aggregateId) {
        this.aggregateId = aggregateId;
    }

    /**
     * Getter for AggregatePathNames.
     * For `siteLevel` aggregation this contains the title for each level in the hierarchy. For
     * other types of aggregation it will be empty.
     * @return Returns the List of String
     */
    @JsonGetter("aggregatePathNames")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getAggregatePathNames() {
        return aggregatePathNames;
    }

    /**
     * Setter for AggregatePathNames.
     * For `siteLevel` aggregation this contains the title for each level in the hierarchy. For
     * other types of aggregation it will be empty.
     * @param aggregatePathNames Value for List of String
     */
    @JsonSetter("aggregatePathNames")
    public void setAggregatePathNames(List<String> aggregatePathNames) {
        this.aggregatePathNames = aggregatePathNames;
    }

    /**
     * Getter for DeviceIds.
     * The ids of the devices in this aggregate group.
     * @return Returns the List of Integer
     */
    @JsonGetter("deviceIds")
    public List<Integer> getDeviceIds() {
        return deviceIds;
    }

    /**
     * Setter for DeviceIds.
     * The ids of the devices in this aggregate group.
     * @param deviceIds Value for List of Integer
     */
    @JsonSetter("deviceIds")
    public void setDeviceIds(List<Integer> deviceIds) {
        this.deviceIds = deviceIds;
    }

    /**
     * Getter for Calculation.
     * @return Returns the CalculationModeRealTime
     */
    @JsonGetter("calculation")
    public CalculationModeRealTime getCalculation() {
        return calculation;
    }

    /**
     * Setter for Calculation.
     * @param calculation Value for CalculationModeRealTime
     */
    @JsonSetter("calculation")
    public void setCalculation(CalculationModeRealTime calculation) {
        this.calculation = calculation;
    }

    /**
     * Getter for DataSignal.
     * @return Returns the DataSignal1
     */
    @JsonGetter("dataSignal")
    public DataSignal1 getDataSignal() {
        return dataSignal;
    }

    /**
     * Setter for DataSignal.
     * @param dataSignal Value for DataSignal1
     */
    @JsonSetter("dataSignal")
    public void setDataSignal(DataSignal1 dataSignal) {
        this.dataSignal = dataSignal;
    }

    /**
     * Getter for Data.
     * A single key value pair with timestamp as key and the data measurement as value. The
     * timestamps are in UTC.
     * @return Returns the Map of String, Double
     */
    @JsonGetter("data")
    public Map<String, Double> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * A single key value pair with timestamp as key and the data measurement as value. The
     * timestamps are in UTC.
     * @param data Value for Map of String, Double
     */
    @JsonSetter("data")
    public void setData(Map<String, Double> data) {
        this.data = data;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DataRealTimeItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DataRealTimeItem [" + "aggregate=" + aggregate + ", aggregateId=" + aggregateId
                + ", deviceIds=" + deviceIds + ", calculation=" + calculation + ", dataSignal="
                + dataSignal + ", data=" + data + ", aggregatePathNames=" + aggregatePathNames
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DataRealTimeItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DataRealTimeItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(aggregate, aggregateId, deviceIds, calculation, dataSignal,
                data)
                .aggregatePathNames(getAggregatePathNames());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DataRealTimeItem}.
     */
    public static class Builder {
        private AggregateMode aggregate;
        private int aggregateId;
        private List<Integer> deviceIds;
        private CalculationModeRealTime calculation;
        private DataSignal1 dataSignal;
        private Map<String, Double> data;
        private List<String> aggregatePathNames;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  aggregate  AggregateMode value for aggregate.
         * @param  aggregateId  int value for aggregateId.
         * @param  deviceIds  List of Integer value for deviceIds.
         * @param  calculation  CalculationModeRealTime value for calculation.
         * @param  dataSignal  DataSignal1 value for dataSignal.
         * @param  data  Map of String, value for data.
         */
        public Builder(AggregateMode aggregate, int aggregateId, List<Integer> deviceIds,
                CalculationModeRealTime calculation, DataSignal1 dataSignal,
                Map<String, Double> data) {
            this.aggregate = aggregate;
            this.aggregateId = aggregateId;
            this.deviceIds = deviceIds;
            this.calculation = calculation;
            this.dataSignal = dataSignal;
            this.data = data;
        }

        /**
         * Setter for aggregate.
         * @param  aggregate  AggregateMode value for aggregate.
         * @return Builder
         */
        public Builder aggregate(AggregateMode aggregate) {
            this.aggregate = aggregate;
            return this;
        }

        /**
         * Setter for aggregateId.
         * @param  aggregateId  int value for aggregateId.
         * @return Builder
         */
        public Builder aggregateId(int aggregateId) {
            this.aggregateId = aggregateId;
            return this;
        }

        /**
         * Setter for deviceIds.
         * @param  deviceIds  List of Integer value for deviceIds.
         * @return Builder
         */
        public Builder deviceIds(List<Integer> deviceIds) {
            this.deviceIds = deviceIds;
            return this;
        }

        /**
         * Setter for calculation.
         * @param  calculation  CalculationModeRealTime value for calculation.
         * @return Builder
         */
        public Builder calculation(CalculationModeRealTime calculation) {
            this.calculation = calculation;
            return this;
        }

        /**
         * Setter for dataSignal.
         * @param  dataSignal  DataSignal1 value for dataSignal.
         * @return Builder
         */
        public Builder dataSignal(DataSignal1 dataSignal) {
            this.dataSignal = dataSignal;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  Map of String, value for data.
         * @return Builder
         */
        public Builder data(Map<String, Double> data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for aggregatePathNames.
         * @param  aggregatePathNames  List of String value for aggregatePathNames.
         * @return Builder
         */
        public Builder aggregatePathNames(List<String> aggregatePathNames) {
            this.aggregatePathNames = aggregatePathNames;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DataRealTimeItem} object using the set fields.
         * @return {@link DataRealTimeItem}
         */
        public DataRealTimeItem build() {
            DataRealTimeItem model =
                    new DataRealTimeItem(aggregate, aggregateId, deviceIds, calculation, dataSignal,
                            data, aggregatePathNames);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
