/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for DataPerCategoryItem type.
 */
public class DataPerCategoryItem {
    private int aggregateId;
    private List<String> aggregatePathNames;
    private List<Integer> deviceIds;
    private String contractTitle;
    private String categoryTitle;
    private CategoryTime categoryTime;
    private double value;
    private Double duration;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DataPerCategoryItem() {
    }

    /**
     * Initialization constructor.
     * @param  aggregateId  int value for aggregateId.
     * @param  deviceIds  List of Integer value for deviceIds.
     * @param  contractTitle  String value for contractTitle.
     * @param  categoryTitle  String value for categoryTitle.
     * @param  categoryTime  CategoryTime value for categoryTime.
     * @param  value  double value for value.
     * @param  aggregatePathNames  List of String value for aggregatePathNames.
     * @param  duration  Double value for duration.
     */
    public DataPerCategoryItem(
            int aggregateId,
            List<Integer> deviceIds,
            String contractTitle,
            String categoryTitle,
            CategoryTime categoryTime,
            double value,
            List<String> aggregatePathNames,
            Double duration) {
        this.aggregateId = aggregateId;
        this.aggregatePathNames = aggregatePathNames;
        this.deviceIds = deviceIds;
        this.contractTitle = contractTitle;
        this.categoryTitle = categoryTitle;
        this.categoryTime = categoryTime;
        this.value = value;
        this.duration = duration;
    }

    /**
     * Getter for AggregateId.
     * The id of this aggregate group: device id, site id, or the constant -1 for portfolio. For
     * `siteLevel` aggregation a generated unique id is used.
     * @return Returns the int
     */
    @JsonGetter("aggregateId")
    public int getAggregateId() {
        return aggregateId;
    }

    /**
     * Setter for AggregateId.
     * The id of this aggregate group: device id, site id, or the constant -1 for portfolio. For
     * `siteLevel` aggregation a generated unique id is used.
     * @param aggregateId Value for int
     */
    @JsonSetter("aggregateId")
    public void setAggregateId(int aggregateId) {
        this.aggregateId = aggregateId;
    }

    /**
     * Getter for AggregatePathNames.
     * For `siteLevel` aggregation this contains the title for each level in the hierarchy. For
     * other types of aggregation it will be empty.
     * @return Returns the List of String
     */
    @JsonGetter("aggregatePathNames")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getAggregatePathNames() {
        return aggregatePathNames;
    }

    /**
     * Setter for AggregatePathNames.
     * For `siteLevel` aggregation this contains the title for each level in the hierarchy. For
     * other types of aggregation it will be empty.
     * @param aggregatePathNames Value for List of String
     */
    @JsonSetter("aggregatePathNames")
    public void setAggregatePathNames(List<String> aggregatePathNames) {
        this.aggregatePathNames = aggregatePathNames;
    }

    /**
     * Getter for DeviceIds.
     * The ids of the devices in this aggregate group.
     * @return Returns the List of Integer
     */
    @JsonGetter("deviceIds")
    public List<Integer> getDeviceIds() {
        return deviceIds;
    }

    /**
     * Setter for DeviceIds.
     * The ids of the devices in this aggregate group.
     * @param deviceIds Value for List of Integer
     */
    @JsonSetter("deviceIds")
    public void setDeviceIds(List<Integer> deviceIds) {
        this.deviceIds = deviceIds;
    }

    /**
     * Getter for ContractTitle.
     * @return Returns the String
     */
    @JsonGetter("contractTitle")
    public String getContractTitle() {
        return contractTitle;
    }

    /**
     * Setter for ContractTitle.
     * @param contractTitle Value for String
     */
    @JsonSetter("contractTitle")
    public void setContractTitle(String contractTitle) {
        this.contractTitle = contractTitle;
    }

    /**
     * Getter for CategoryTitle.
     * @return Returns the String
     */
    @JsonGetter("categoryTitle")
    public String getCategoryTitle() {
        return categoryTitle;
    }

    /**
     * Setter for CategoryTitle.
     * @param categoryTitle Value for String
     */
    @JsonSetter("categoryTitle")
    public void setCategoryTitle(String categoryTitle) {
        this.categoryTitle = categoryTitle;
    }

    /**
     * Getter for CategoryTime.
     * @return Returns the CategoryTime
     */
    @JsonGetter("categoryTime")
    public CategoryTime getCategoryTime() {
        return categoryTime;
    }

    /**
     * Setter for CategoryTime.
     * @param categoryTime Value for CategoryTime
     */
    @JsonSetter("categoryTime")
    public void setCategoryTime(CategoryTime categoryTime) {
        this.categoryTime = categoryTime;
    }

    /**
     * Getter for Value.
     * The aggregated value of the selected data signal.
     * @return Returns the double
     */
    @JsonGetter("value")
    public double getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * The aggregated value of the selected data signal.
     * @param value Value for double
     */
    @JsonSetter("value")
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Getter for Duration.
     * The summed duration in seconds allocated to this contract category and aggregate group.
     * @return Returns the Double
     */
    @JsonGetter("duration")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getDuration() {
        return duration;
    }

    /**
     * Setter for Duration.
     * The summed duration in seconds allocated to this contract category and aggregate group.
     * @param duration Value for Double
     */
    @JsonSetter("duration")
    public void setDuration(Double duration) {
        this.duration = duration;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DataPerCategoryItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DataPerCategoryItem [" + "aggregateId=" + aggregateId + ", deviceIds=" + deviceIds
                + ", contractTitle=" + contractTitle + ", categoryTitle=" + categoryTitle
                + ", categoryTime=" + categoryTime + ", value=" + value + ", aggregatePathNames="
                + aggregatePathNames + ", duration=" + duration + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DataPerCategoryItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DataPerCategoryItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(aggregateId, deviceIds, contractTitle, categoryTitle,
                categoryTime, value)
                .aggregatePathNames(getAggregatePathNames())
                .duration(getDuration());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DataPerCategoryItem}.
     */
    public static class Builder {
        private int aggregateId;
        private List<Integer> deviceIds;
        private String contractTitle;
        private String categoryTitle;
        private CategoryTime categoryTime;
        private double value;
        private List<String> aggregatePathNames;
        private Double duration;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  aggregateId  int value for aggregateId.
         * @param  deviceIds  List of Integer value for deviceIds.
         * @param  contractTitle  String value for contractTitle.
         * @param  categoryTitle  String value for categoryTitle.
         * @param  categoryTime  CategoryTime value for categoryTime.
         * @param  value  double value for value.
         */
        public Builder(int aggregateId, List<Integer> deviceIds, String contractTitle,
                String categoryTitle, CategoryTime categoryTime, double value) {
            this.aggregateId = aggregateId;
            this.deviceIds = deviceIds;
            this.contractTitle = contractTitle;
            this.categoryTitle = categoryTitle;
            this.categoryTime = categoryTime;
            this.value = value;
        }

        /**
         * Setter for aggregateId.
         * @param  aggregateId  int value for aggregateId.
         * @return Builder
         */
        public Builder aggregateId(int aggregateId) {
            this.aggregateId = aggregateId;
            return this;
        }

        /**
         * Setter for deviceIds.
         * @param  deviceIds  List of Integer value for deviceIds.
         * @return Builder
         */
        public Builder deviceIds(List<Integer> deviceIds) {
            this.deviceIds = deviceIds;
            return this;
        }

        /**
         * Setter for contractTitle.
         * @param  contractTitle  String value for contractTitle.
         * @return Builder
         */
        public Builder contractTitle(String contractTitle) {
            this.contractTitle = contractTitle;
            return this;
        }

        /**
         * Setter for categoryTitle.
         * @param  categoryTitle  String value for categoryTitle.
         * @return Builder
         */
        public Builder categoryTitle(String categoryTitle) {
            this.categoryTitle = categoryTitle;
            return this;
        }

        /**
         * Setter for categoryTime.
         * @param  categoryTime  CategoryTime value for categoryTime.
         * @return Builder
         */
        public Builder categoryTime(CategoryTime categoryTime) {
            this.categoryTime = categoryTime;
            return this;
        }

        /**
         * Setter for value.
         * @param  value  double value for value.
         * @return Builder
         */
        public Builder value(double value) {
            this.value = value;
            return this;
        }

        /**
         * Setter for aggregatePathNames.
         * @param  aggregatePathNames  List of String value for aggregatePathNames.
         * @return Builder
         */
        public Builder aggregatePathNames(List<String> aggregatePathNames) {
            this.aggregatePathNames = aggregatePathNames;
            return this;
        }

        /**
         * Setter for duration.
         * @param  duration  Double value for duration.
         * @return Builder
         */
        public Builder duration(Double duration) {
            this.duration = duration;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DataPerCategoryItem} object using the set fields.
         * @return {@link DataPerCategoryItem}
         */
        public DataPerCategoryItem build() {
            DataPerCategoryItem model =
                    new DataPerCategoryItem(aggregateId, deviceIds, contractTitle, categoryTitle,
                            categoryTime, value, aggregatePathNames, duration);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
