/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for DataPerCategoryResponse type.
 */
public class DataPerCategoryResponse {
    private DataSignal1 dataSignal;
    private CalculationMode calculation;
    private List<DataPerCategoryItem> data;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DataPerCategoryResponse() {
    }

    /**
     * Initialization constructor.
     * @param  dataSignal  DataSignal1 value for dataSignal.
     * @param  calculation  CalculationMode value for calculation.
     * @param  data  List of DataPerCategoryItem value for data.
     */
    public DataPerCategoryResponse(
            DataSignal1 dataSignal,
            CalculationMode calculation,
            List<DataPerCategoryItem> data) {
        this.dataSignal = dataSignal;
        this.calculation = calculation;
        this.data = data;
    }

    /**
     * Getter for DataSignal.
     * @return Returns the DataSignal1
     */
    @JsonGetter("dataSignal")
    public DataSignal1 getDataSignal() {
        return dataSignal;
    }

    /**
     * Setter for DataSignal.
     * @param dataSignal Value for DataSignal1
     */
    @JsonSetter("dataSignal")
    public void setDataSignal(DataSignal1 dataSignal) {
        this.dataSignal = dataSignal;
    }

    /**
     * Getter for Calculation.
     * @return Returns the CalculationMode
     */
    @JsonGetter("calculation")
    public CalculationMode getCalculation() {
        return calculation;
    }

    /**
     * Setter for Calculation.
     * @param calculation Value for CalculationMode
     */
    @JsonSetter("calculation")
    public void setCalculation(CalculationMode calculation) {
        this.calculation = calculation;
    }

    /**
     * Getter for Data.
     * A list of objects: one per combination of * aggregate * contract category
     * @return Returns the List of DataPerCategoryItem
     */
    @JsonGetter("data")
    public List<DataPerCategoryItem> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * A list of objects: one per combination of * aggregate * contract category
     * @param data Value for List of DataPerCategoryItem
     */
    @JsonSetter("data")
    public void setData(List<DataPerCategoryItem> data) {
        this.data = data;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DataPerCategoryResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DataPerCategoryResponse [" + "dataSignal=" + dataSignal + ", calculation="
                + calculation + ", data=" + data + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link DataPerCategoryResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DataPerCategoryResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(dataSignal, calculation, data);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DataPerCategoryResponse}.
     */
    public static class Builder {
        private DataSignal1 dataSignal;
        private CalculationMode calculation;
        private List<DataPerCategoryItem> data;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  dataSignal  DataSignal1 value for dataSignal.
         * @param  calculation  CalculationMode value for calculation.
         * @param  data  List of DataPerCategoryItem value for data.
         */
        public Builder(DataSignal1 dataSignal, CalculationMode calculation,
                List<DataPerCategoryItem> data) {
            this.dataSignal = dataSignal;
            this.calculation = calculation;
            this.data = data;
        }

        /**
         * Setter for dataSignal.
         * @param  dataSignal  DataSignal1 value for dataSignal.
         * @return Builder
         */
        public Builder dataSignal(DataSignal1 dataSignal) {
            this.dataSignal = dataSignal;
            return this;
        }

        /**
         * Setter for calculation.
         * @param  calculation  CalculationMode value for calculation.
         * @return Builder
         */
        public Builder calculation(CalculationMode calculation) {
            this.calculation = calculation;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  List of DataPerCategoryItem value for data.
         * @return Builder
         */
        public Builder data(List<DataPerCategoryItem> data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DataPerCategoryResponse} object using the set fields.
         * @return {@link DataPerCategoryResponse}
         */
        public DataPerCategoryResponse build() {
            DataPerCategoryResponse model =
                    new DataPerCategoryResponse(dataSignal, calculation, data);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
