/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for DataSignals type.
 */
public class DataSignals {
    private int availabilityTimeDataSignalId;
    private int availabilityProductionDataSignalId;
    private int lostProductionDataSignalId;
    private int performanceDataSignalId;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DataSignals() {
    }

    /**
     * Initialization constructor.
     * @param  availabilityTimeDataSignalId  int value for availabilityTimeDataSignalId.
     * @param  availabilityProductionDataSignalId  int value for availabilityProductionDataSignalId.
     * @param  lostProductionDataSignalId  int value for lostProductionDataSignalId.
     * @param  performanceDataSignalId  int value for performanceDataSignalId.
     */
    public DataSignals(
            int availabilityTimeDataSignalId,
            int availabilityProductionDataSignalId,
            int lostProductionDataSignalId,
            int performanceDataSignalId) {
        this.availabilityTimeDataSignalId = availabilityTimeDataSignalId;
        this.availabilityProductionDataSignalId = availabilityProductionDataSignalId;
        this.lostProductionDataSignalId = lostProductionDataSignalId;
        this.performanceDataSignalId = performanceDataSignalId;
    }

    /**
     * Getter for AvailabilityTimeDataSignalId.
     * The id of the data signal used for time-based availability data.
     * @return Returns the int
     */
    @JsonGetter("availabilityTimeDataSignalId")
    public int getAvailabilityTimeDataSignalId() {
        return availabilityTimeDataSignalId;
    }

    /**
     * Setter for AvailabilityTimeDataSignalId.
     * The id of the data signal used for time-based availability data.
     * @param availabilityTimeDataSignalId Value for int
     */
    @JsonSetter("availabilityTimeDataSignalId")
    public void setAvailabilityTimeDataSignalId(int availabilityTimeDataSignalId) {
        this.availabilityTimeDataSignalId = availabilityTimeDataSignalId;
    }

    /**
     * Getter for AvailabilityProductionDataSignalId.
     * The id of the data signal used for production-based availability data.
     * @return Returns the int
     */
    @JsonGetter("availabilityProductionDataSignalId")
    public int getAvailabilityProductionDataSignalId() {
        return availabilityProductionDataSignalId;
    }

    /**
     * Setter for AvailabilityProductionDataSignalId.
     * The id of the data signal used for production-based availability data.
     * @param availabilityProductionDataSignalId Value for int
     */
    @JsonSetter("availabilityProductionDataSignalId")
    public void setAvailabilityProductionDataSignalId(int availabilityProductionDataSignalId) {
        this.availabilityProductionDataSignalId = availabilityProductionDataSignalId;
    }

    /**
     * Getter for LostProductionDataSignalId.
     * The id of the data signal used for lost production data.
     * @return Returns the int
     */
    @JsonGetter("lostProductionDataSignalId")
    public int getLostProductionDataSignalId() {
        return lostProductionDataSignalId;
    }

    /**
     * Setter for LostProductionDataSignalId.
     * The id of the data signal used for lost production data.
     * @param lostProductionDataSignalId Value for int
     */
    @JsonSetter("lostProductionDataSignalId")
    public void setLostProductionDataSignalId(int lostProductionDataSignalId) {
        this.lostProductionDataSignalId = lostProductionDataSignalId;
    }

    /**
     * Getter for PerformanceDataSignalId.
     * The id of the data signal used for performance data.
     * @return Returns the int
     */
    @JsonGetter("performanceDataSignalId")
    public int getPerformanceDataSignalId() {
        return performanceDataSignalId;
    }

    /**
     * Setter for PerformanceDataSignalId.
     * The id of the data signal used for performance data.
     * @param performanceDataSignalId Value for int
     */
    @JsonSetter("performanceDataSignalId")
    public void setPerformanceDataSignalId(int performanceDataSignalId) {
        this.performanceDataSignalId = performanceDataSignalId;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DataSignals into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DataSignals [" + "availabilityTimeDataSignalId=" + availabilityTimeDataSignalId
                + ", availabilityProductionDataSignalId=" + availabilityProductionDataSignalId
                + ", lostProductionDataSignalId=" + lostProductionDataSignalId
                + ", performanceDataSignalId=" + performanceDataSignalId + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DataSignals.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DataSignals.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(availabilityTimeDataSignalId,
                availabilityProductionDataSignalId, lostProductionDataSignalId,
                performanceDataSignalId);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DataSignals}.
     */
    public static class Builder {
        private int availabilityTimeDataSignalId;
        private int availabilityProductionDataSignalId;
        private int lostProductionDataSignalId;
        private int performanceDataSignalId;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  availabilityTimeDataSignalId  int value for availabilityTimeDataSignalId.
         * @param  availabilityProductionDataSignalId  int value for
         *         availabilityProductionDataSignalId.
         * @param  lostProductionDataSignalId  int value for lostProductionDataSignalId.
         * @param  performanceDataSignalId  int value for performanceDataSignalId.
         */
        public Builder(int availabilityTimeDataSignalId, int availabilityProductionDataSignalId,
                int lostProductionDataSignalId, int performanceDataSignalId) {
            this.availabilityTimeDataSignalId = availabilityTimeDataSignalId;
            this.availabilityProductionDataSignalId = availabilityProductionDataSignalId;
            this.lostProductionDataSignalId = lostProductionDataSignalId;
            this.performanceDataSignalId = performanceDataSignalId;
        }

        /**
         * Setter for availabilityTimeDataSignalId.
         * @param  availabilityTimeDataSignalId  int value for availabilityTimeDataSignalId.
         * @return Builder
         */
        public Builder availabilityTimeDataSignalId(int availabilityTimeDataSignalId) {
            this.availabilityTimeDataSignalId = availabilityTimeDataSignalId;
            return this;
        }

        /**
         * Setter for availabilityProductionDataSignalId.
         * @param  availabilityProductionDataSignalId  int value for
         *         availabilityProductionDataSignalId.
         * @return Builder
         */
        public Builder availabilityProductionDataSignalId(
                int availabilityProductionDataSignalId) {
            this.availabilityProductionDataSignalId = availabilityProductionDataSignalId;
            return this;
        }

        /**
         * Setter for lostProductionDataSignalId.
         * @param  lostProductionDataSignalId  int value for lostProductionDataSignalId.
         * @return Builder
         */
        public Builder lostProductionDataSignalId(int lostProductionDataSignalId) {
            this.lostProductionDataSignalId = lostProductionDataSignalId;
            return this;
        }

        /**
         * Setter for performanceDataSignalId.
         * @param  performanceDataSignalId  int value for performanceDataSignalId.
         * @return Builder
         */
        public Builder performanceDataSignalId(int performanceDataSignalId) {
            this.performanceDataSignalId = performanceDataSignalId;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DataSignals} object using the set fields.
         * @return {@link DataSignals}
         */
        public DataSignals build() {
            DataSignals model =
                    new DataSignals(availabilityTimeDataSignalId,
                            availabilityProductionDataSignalId, lostProductionDataSignalId,
                            performanceDataSignalId);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
