/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for DevicesPublishedAfterDateResponse type.
 */
public class DevicesPublishedAfterDateResponse {
    private Integer numberOfDevices;
    private List<Integer> authorizedDeviceIds;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DevicesPublishedAfterDateResponse() {
    }

    /**
     * Initialization constructor.
     * @param  numberOfDevices  Integer value for numberOfDevices.
     * @param  authorizedDeviceIds  List of Integer value for authorizedDeviceIds.
     */
    public DevicesPublishedAfterDateResponse(
            Integer numberOfDevices,
            List<Integer> authorizedDeviceIds) {
        this.numberOfDevices = numberOfDevices;
        this.authorizedDeviceIds = authorizedDeviceIds;
    }

    /**
     * Getter for NumberOfDevices.
     * The id of a site.
     * @return Returns the Integer
     */
    @JsonGetter("numberOfDevices")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumberOfDevices() {
        return numberOfDevices;
    }

    /**
     * Setter for NumberOfDevices.
     * The id of a site.
     * @param numberOfDevices Value for Integer
     */
    @JsonSetter("numberOfDevices")
    public void setNumberOfDevices(Integer numberOfDevices) {
        this.numberOfDevices = numberOfDevices;
    }

    /**
     * Getter for AuthorizedDeviceIds.
     * @return Returns the List of Integer
     */
    @JsonGetter("authorizedDeviceIds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getAuthorizedDeviceIds() {
        return authorizedDeviceIds;
    }

    /**
     * Setter for AuthorizedDeviceIds.
     * @param authorizedDeviceIds Value for List of Integer
     */
    @JsonSetter("authorizedDeviceIds")
    public void setAuthorizedDeviceIds(List<Integer> authorizedDeviceIds) {
        this.authorizedDeviceIds = authorizedDeviceIds;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DevicesPublishedAfterDateResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DevicesPublishedAfterDateResponse [" + "numberOfDevices=" + numberOfDevices
                + ", authorizedDeviceIds=" + authorizedDeviceIds + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DevicesPublishedAfterDateResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DevicesPublishedAfterDateResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .numberOfDevices(getNumberOfDevices())
                .authorizedDeviceIds(getAuthorizedDeviceIds());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DevicesPublishedAfterDateResponse}.
     */
    public static class Builder {
        private Integer numberOfDevices;
        private List<Integer> authorizedDeviceIds;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for numberOfDevices.
         * @param  numberOfDevices  Integer value for numberOfDevices.
         * @return Builder
         */
        public Builder numberOfDevices(Integer numberOfDevices) {
            this.numberOfDevices = numberOfDevices;
            return this;
        }

        /**
         * Setter for authorizedDeviceIds.
         * @param  authorizedDeviceIds  List of Integer value for authorizedDeviceIds.
         * @return Builder
         */
        public Builder authorizedDeviceIds(List<Integer> authorizedDeviceIds) {
            this.authorizedDeviceIds = authorizedDeviceIds;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DevicesPublishedAfterDateResponse} object using the set fields.
         * @return {@link DevicesPublishedAfterDateResponse}
         */
        public DevicesPublishedAfterDateResponse build() {
            DevicesPublishedAfterDateResponse model =
                    new DevicesPublishedAfterDateResponse(numberOfDevices, authorizedDeviceIds);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
