/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for HighresdataResponse type.
 */
public class HighresdataResponse {
    private int deviceId;
    private DataSignal1 dataSignal;
    private Map<String, Double> data;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public HighresdataResponse() {
    }

    /**
     * Initialization constructor.
     * @param  deviceId  int value for deviceId.
     * @param  dataSignal  DataSignal1 value for dataSignal.
     * @param  data  Map of String, value for data.
     */
    public HighresdataResponse(
            int deviceId,
            DataSignal1 dataSignal,
            Map<String, Double> data) {
        this.deviceId = deviceId;
        this.dataSignal = dataSignal;
        this.data = data;
    }

    /**
     * Getter for DeviceId.
     * The id of a device.
     * @return Returns the int
     */
    @JsonGetter("deviceId")
    public int getDeviceId() {
        return deviceId;
    }

    /**
     * Setter for DeviceId.
     * The id of a device.
     * @param deviceId Value for int
     */
    @JsonSetter("deviceId")
    public void setDeviceId(int deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Getter for DataSignal.
     * @return Returns the DataSignal1
     */
    @JsonGetter("dataSignal")
    public DataSignal1 getDataSignal() {
        return dataSignal;
    }

    /**
     * Setter for DataSignal.
     * @param dataSignal Value for DataSignal1
     */
    @JsonSetter("dataSignal")
    public void setDataSignal(DataSignal1 dataSignal) {
        this.dataSignal = dataSignal;
    }

    /**
     * Getter for Data.
     * One or more key value pairs with timestamp as key and the data measurement as value. The
     * timestamps are in UTC.
     * @return Returns the Map of String, Double
     */
    @JsonGetter("data")
    public Map<String, Double> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * One or more key value pairs with timestamp as key and the data measurement as value. The
     * timestamps are in UTC.
     * @param data Value for Map of String, Double
     */
    @JsonSetter("data")
    public void setData(Map<String, Double> data) {
        this.data = data;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this HighresdataResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HighresdataResponse [" + "deviceId=" + deviceId + ", dataSignal=" + dataSignal
                + ", data=" + data + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link HighresdataResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link HighresdataResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(deviceId, dataSignal, data);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link HighresdataResponse}.
     */
    public static class Builder {
        private int deviceId;
        private DataSignal1 dataSignal;
        private Map<String, Double> data;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  deviceId  int value for deviceId.
         * @param  dataSignal  DataSignal1 value for dataSignal.
         * @param  data  Map of String, value for data.
         */
        public Builder(int deviceId, DataSignal1 dataSignal, Map<String, Double> data) {
            this.deviceId = deviceId;
            this.dataSignal = dataSignal;
            this.data = data;
        }

        /**
         * Setter for deviceId.
         * @param  deviceId  int value for deviceId.
         * @return Builder
         */
        public Builder deviceId(int deviceId) {
            this.deviceId = deviceId;
            return this;
        }

        /**
         * Setter for dataSignal.
         * @param  dataSignal  DataSignal1 value for dataSignal.
         * @return Builder
         */
        public Builder dataSignal(DataSignal1 dataSignal) {
            this.dataSignal = dataSignal;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  Map of String, value for data.
         * @return Builder
         */
        public Builder data(Map<String, Double> data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link HighresdataResponse} object using the set fields.
         * @return {@link HighresdataResponse}
         */
        public HighresdataResponse build() {
            HighresdataResponse model =
                    new HighresdataResponse(deviceId, dataSignal, data);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
