/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * HseCategory to be used.
 */
public enum HseCategory {
    ACCIDENT,

    NEARMISS,

    HAZARDOBSERVATION,

    ENVIRONMENTAL;

    private static TreeMap<String, HseCategory> valueMap = new TreeMap<>();
    private String value;

    static {
        ACCIDENT.value = "Accident";
        NEARMISS.value = "NearMiss";
        HAZARDOBSERVATION.value = "HazardObservation";
        ENVIRONMENTAL.value = "Environmental";

        valueMap.put("Accident", ACCIDENT);
        valueMap.put("NearMiss", NEARMISS);
        valueMap.put("HazardObservation", HAZARDOBSERVATION);
        valueMap.put("Environmental", ENVIRONMENTAL);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static HseCategory constructFromString(String toConvert) throws IOException {
        HseCategory enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static HseCategory fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of HseCategory values to list of string values.
     * @param toConvert The list of HseCategory values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<HseCategory> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (HseCategory enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 