/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for LostProductionSignal type.
 */
public class LostProductionSignal {
    private int dataSignalId;
    private String title;
    private String unit;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public LostProductionSignal() {
    }

    /**
     * Initialization constructor.
     * @param  dataSignalId  int value for dataSignalId.
     * @param  title  String value for title.
     * @param  unit  String value for unit.
     */
    public LostProductionSignal(
            int dataSignalId,
            String title,
            String unit) {
        this.dataSignalId = dataSignalId;
        this.title = title;
        this.unit = unit;
    }

    /**
     * Getter for DataSignalId.
     * The unique id of a data signal.
     * @return Returns the int
     */
    @JsonGetter("dataSignalId")
    public int getDataSignalId() {
        return dataSignalId;
    }

    /**
     * Setter for DataSignalId.
     * The unique id of a data signal.
     * @param dataSignalId Value for int
     */
    @JsonSetter("dataSignalId")
    public void setDataSignalId(int dataSignalId) {
        this.dataSignalId = dataSignalId;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for Unit.
     * @return Returns the String
     */
    @JsonGetter("unit")
    public String getUnit() {
        return unit;
    }

    /**
     * Setter for Unit.
     * @param unit Value for String
     */
    @JsonSetter("unit")
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this LostProductionSignal into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LostProductionSignal [" + "dataSignalId=" + dataSignalId + ", title=" + title
                + ", unit=" + unit + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link LostProductionSignal.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LostProductionSignal.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(dataSignalId, title, unit);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link LostProductionSignal}.
     */
    public static class Builder {
        private int dataSignalId;
        private String title;
        private String unit;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  dataSignalId  int value for dataSignalId.
         * @param  title  String value for title.
         * @param  unit  String value for unit.
         */
        public Builder(int dataSignalId, String title, String unit) {
            this.dataSignalId = dataSignalId;
            this.title = title;
            this.unit = unit;
        }

        /**
         * Setter for dataSignalId.
         * @param  dataSignalId  int value for dataSignalId.
         * @return Builder
         */
        public Builder dataSignalId(int dataSignalId) {
            this.dataSignalId = dataSignalId;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for unit.
         * @param  unit  String value for unit.
         * @return Builder
         */
        public Builder unit(String unit) {
            this.unit = unit;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link LostProductionSignal} object using the set fields.
         * @return {@link LostProductionSignal}
         */
        public LostProductionSignal build() {
            LostProductionSignal model =
                    new LostProductionSignal(dataSignalId, title, unit);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
