/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Organization1 type.
 */
public class Organization1 {
    private Integer organizationId;
    private String name;
    private String email;
    private String phone;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Organization1() {
    }

    /**
     * Initialization constructor.
     * @param  organizationId  Integer value for organizationId.
     * @param  name  String value for name.
     * @param  email  String value for email.
     * @param  phone  String value for phone.
     */
    public Organization1(
            Integer organizationId,
            String name,
            String email,
            String phone) {
        this.organizationId = organizationId;
        this.name = name;
        this.email = email;
        this.phone = phone;
    }

    /**
     * Getter for OrganizationId.
     * An id of an organization used for tasks and personnel.
     * @return Returns the Integer
     */
    @JsonGetter("organizationId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * Setter for OrganizationId.
     * An id of an organization used for tasks and personnel.
     * @param organizationId Value for Integer
     */
    @JsonSetter("organizationId")
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Email.
     * @return Returns the String
     */
    @JsonGetter("email")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * @param email Value for String
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for Phone.
     * @return Returns the String
     */
    @JsonGetter("phone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPhone() {
        return phone;
    }

    /**
     * Setter for Phone.
     * @param phone Value for String
     */
    @JsonSetter("phone")
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Organization1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Organization1 [" + "organizationId=" + organizationId + ", name=" + name
                + ", email=" + email + ", phone=" + phone + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Organization1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Organization1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .organizationId(getOrganizationId())
                .name(getName())
                .email(getEmail())
                .phone(getPhone());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Organization1}.
     */
    public static class Builder {
        private Integer organizationId;
        private String name;
        private String email;
        private String phone;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for organizationId.
         * @param  organizationId  Integer value for organizationId.
         * @return Builder
         */
        public Builder organizationId(Integer organizationId) {
            this.organizationId = organizationId;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for phone.
         * @param  phone  String value for phone.
         * @return Builder
         */
        public Builder phone(String phone) {
            this.phone = phone;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Organization1} object using the set fields.
         * @return {@link Organization1}
         */
        public Organization1 build() {
            Organization1 model =
                    new Organization1(organizationId, name, email, phone);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
