/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PersonnelQualification type.
 */
public class PersonnelQualification {
    private Integer qualificationId;
    private String manufacturer;
    private String qualificationType;
    private String qualificationDescription;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PersonnelQualification() {
    }

    /**
     * Initialization constructor.
     * @param  qualificationId  Integer value for qualificationId.
     * @param  manufacturer  String value for manufacturer.
     * @param  qualificationType  String value for qualificationType.
     * @param  qualificationDescription  String value for qualificationDescription.
     */
    public PersonnelQualification(
            Integer qualificationId,
            String manufacturer,
            String qualificationType,
            String qualificationDescription) {
        this.qualificationId = qualificationId;
        this.manufacturer = manufacturer;
        this.qualificationType = qualificationType;
        this.qualificationDescription = qualificationDescription;
    }

    /**
     * Getter for QualificationId.
     * The id of a personnel qualification.
     * @return Returns the Integer
     */
    @JsonGetter("qualificationId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getQualificationId() {
        return qualificationId;
    }

    /**
     * Setter for QualificationId.
     * The id of a personnel qualification.
     * @param qualificationId Value for Integer
     */
    @JsonSetter("qualificationId")
    public void setQualificationId(Integer qualificationId) {
        this.qualificationId = qualificationId;
    }

    /**
     * Getter for Manufacturer.
     * @return Returns the String
     */
    @JsonGetter("manufacturer")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Setter for Manufacturer.
     * @param manufacturer Value for String
     */
    @JsonSetter("manufacturer")
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     * Getter for QualificationType.
     * @return Returns the String
     */
    @JsonGetter("qualificationType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getQualificationType() {
        return qualificationType;
    }

    /**
     * Setter for QualificationType.
     * @param qualificationType Value for String
     */
    @JsonSetter("qualificationType")
    public void setQualificationType(String qualificationType) {
        this.qualificationType = qualificationType;
    }

    /**
     * Getter for QualificationDescription.
     * @return Returns the String
     */
    @JsonGetter("qualificationDescription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getQualificationDescription() {
        return qualificationDescription;
    }

    /**
     * Setter for QualificationDescription.
     * @param qualificationDescription Value for String
     */
    @JsonSetter("qualificationDescription")
    public void setQualificationDescription(String qualificationDescription) {
        this.qualificationDescription = qualificationDescription;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PersonnelQualification into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PersonnelQualification [" + "qualificationId=" + qualificationId + ", manufacturer="
                + manufacturer + ", qualificationType=" + qualificationType
                + ", qualificationDescription=" + qualificationDescription
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PersonnelQualification.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PersonnelQualification.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .qualificationId(getQualificationId())
                .manufacturer(getManufacturer())
                .qualificationType(getQualificationType())
                .qualificationDescription(getQualificationDescription());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PersonnelQualification}.
     */
    public static class Builder {
        private Integer qualificationId;
        private String manufacturer;
        private String qualificationType;
        private String qualificationDescription;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for qualificationId.
         * @param  qualificationId  Integer value for qualificationId.
         * @return Builder
         */
        public Builder qualificationId(Integer qualificationId) {
            this.qualificationId = qualificationId;
            return this;
        }

        /**
         * Setter for manufacturer.
         * @param  manufacturer  String value for manufacturer.
         * @return Builder
         */
        public Builder manufacturer(String manufacturer) {
            this.manufacturer = manufacturer;
            return this;
        }

        /**
         * Setter for qualificationType.
         * @param  qualificationType  String value for qualificationType.
         * @return Builder
         */
        public Builder qualificationType(String qualificationType) {
            this.qualificationType = qualificationType;
            return this;
        }

        /**
         * Setter for qualificationDescription.
         * @param  qualificationDescription  String value for qualificationDescription.
         * @return Builder
         */
        public Builder qualificationDescription(String qualificationDescription) {
            this.qualificationDescription = qualificationDescription;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PersonnelQualification} object using the set fields.
         * @return {@link PersonnelQualification}
         */
        public PersonnelQualification build() {
            PersonnelQualification model =
                    new PersonnelQualification(qualificationId, manufacturer, qualificationType,
                            qualificationDescription);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
