/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Personnel type.
 */
public class Personnel {
    private Integer personnelId;
    private String firstName;
    private String lastName;
    private OptionalNullable<String> email;
    private OptionalNullable<String> phone;
    private OptionalNullable<String> mobile;
    private Organization1 organization;
    private List<PersonnelQualification> qualifications;
    private List<PersonnelSiteInduction> siteInductions;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Personnel() {
    }

    /**
     * Initialization constructor.
     * @param  personnelId  Integer value for personnelId.
     * @param  firstName  String value for firstName.
     * @param  lastName  String value for lastName.
     * @param  email  String value for email.
     * @param  phone  String value for phone.
     * @param  mobile  String value for mobile.
     * @param  organization  Organization1 value for organization.
     * @param  qualifications  List of PersonnelQualification value for qualifications.
     * @param  siteInductions  List of PersonnelSiteInduction value for siteInductions.
     */
    public Personnel(
            Integer personnelId,
            String firstName,
            String lastName,
            String email,
            String phone,
            String mobile,
            Organization1 organization,
            List<PersonnelQualification> qualifications,
            List<PersonnelSiteInduction> siteInductions) {
        this.personnelId = personnelId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = OptionalNullable.of(email);
        this.phone = OptionalNullable.of(phone);
        this.mobile = OptionalNullable.of(mobile);
        this.organization = organization;
        this.qualifications = qualifications;
        this.siteInductions = siteInductions;
    }

    /**
     * Initialization constructor.
     * @param  personnelId  Integer value for personnelId.
     * @param  firstName  String value for firstName.
     * @param  lastName  String value for lastName.
     * @param  email  String value for email.
     * @param  phone  String value for phone.
     * @param  mobile  String value for mobile.
     * @param  organization  Organization1 value for organization.
     * @param  qualifications  List of PersonnelQualification value for qualifications.
     * @param  siteInductions  List of PersonnelSiteInduction value for siteInductions.
     */

    protected Personnel(Integer personnelId, String firstName, String lastName,
            OptionalNullable<String> email, OptionalNullable<String> phone,
            OptionalNullable<String> mobile, Organization1 organization,
            List<PersonnelQualification> qualifications,
            List<PersonnelSiteInduction> siteInductions) {
        this.personnelId = personnelId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.mobile = mobile;
        this.organization = organization;
        this.qualifications = qualifications;
        this.siteInductions = siteInductions;
    }

    /**
     * Getter for PersonnelId.
     * The id of a person in the personnel list.
     * @return Returns the Integer
     */
    @JsonGetter("personnelId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPersonnelId() {
        return personnelId;
    }

    /**
     * Setter for PersonnelId.
     * The id of a person in the personnel list.
     * @param personnelId Value for Integer
     */
    @JsonSetter("personnelId")
    public void setPersonnelId(Integer personnelId) {
        this.personnelId = personnelId;
    }

    /**
     * Getter for FirstName.
     * @return Returns the String
     */
    @JsonGetter("firstName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFirstName() {
        return firstName;
    }

    /**
     * Setter for FirstName.
     * @param firstName Value for String
     */
    @JsonSetter("firstName")
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for LastName.
     * @return Returns the String
     */
    @JsonGetter("lastName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastName() {
        return lastName;
    }

    /**
     * Setter for LastName.
     * @param lastName Value for String
     */
    @JsonSetter("lastName")
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Internal Getter for Email.
     * @return Returns the Internal String
     */
    @JsonGetter("email")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetEmail() {
        return this.email;
    }

    /**
     * Getter for Email.
     * @return Returns the String
     */
    public String getEmail() {
        return OptionalNullable.getFrom(email);
    }

    /**
     * Setter for Email.
     * @param email Value for String
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = OptionalNullable.of(email);
    }

    /**
     * UnSetter for Email.
     */
    public void unsetEmail() {
        email = null;
    }

    /**
     * Internal Getter for Phone.
     * @return Returns the Internal String
     */
    @JsonGetter("phone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetPhone() {
        return this.phone;
    }

    /**
     * Getter for Phone.
     * @return Returns the String
     */
    public String getPhone() {
        return OptionalNullable.getFrom(phone);
    }

    /**
     * Setter for Phone.
     * @param phone Value for String
     */
    @JsonSetter("phone")
    public void setPhone(String phone) {
        this.phone = OptionalNullable.of(phone);
    }

    /**
     * UnSetter for Phone.
     */
    public void unsetPhone() {
        phone = null;
    }

    /**
     * Internal Getter for Mobile.
     * @return Returns the Internal String
     */
    @JsonGetter("mobile")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetMobile() {
        return this.mobile;
    }

    /**
     * Getter for Mobile.
     * @return Returns the String
     */
    public String getMobile() {
        return OptionalNullable.getFrom(mobile);
    }

    /**
     * Setter for Mobile.
     * @param mobile Value for String
     */
    @JsonSetter("mobile")
    public void setMobile(String mobile) {
        this.mobile = OptionalNullable.of(mobile);
    }

    /**
     * UnSetter for Mobile.
     */
    public void unsetMobile() {
        mobile = null;
    }

    /**
     * Getter for Organization.
     * @return Returns the Organization1
     */
    @JsonGetter("organization")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Organization1 getOrganization() {
        return organization;
    }

    /**
     * Setter for Organization.
     * @param organization Value for Organization1
     */
    @JsonSetter("organization")
    public void setOrganization(Organization1 organization) {
        this.organization = organization;
    }

    /**
     * Getter for Qualifications.
     * @return Returns the List of PersonnelQualification
     */
    @JsonGetter("qualifications")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<PersonnelQualification> getQualifications() {
        return qualifications;
    }

    /**
     * Setter for Qualifications.
     * @param qualifications Value for List of PersonnelQualification
     */
    @JsonSetter("qualifications")
    public void setQualifications(List<PersonnelQualification> qualifications) {
        this.qualifications = qualifications;
    }

    /**
     * Getter for SiteInductions.
     * @return Returns the List of PersonnelSiteInduction
     */
    @JsonGetter("siteInductions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<PersonnelSiteInduction> getSiteInductions() {
        return siteInductions;
    }

    /**
     * Setter for SiteInductions.
     * @param siteInductions Value for List of PersonnelSiteInduction
     */
    @JsonSetter("siteInductions")
    public void setSiteInductions(List<PersonnelSiteInduction> siteInductions) {
        this.siteInductions = siteInductions;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Personnel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Personnel [" + "personnelId=" + personnelId + ", firstName=" + firstName
                + ", lastName=" + lastName + ", email=" + email + ", phone=" + phone + ", mobile="
                + mobile + ", organization=" + organization + ", qualifications=" + qualifications
                + ", siteInductions=" + siteInductions + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Personnel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Personnel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .personnelId(getPersonnelId())
                .firstName(getFirstName())
                .lastName(getLastName())
                .organization(getOrganization())
                .qualifications(getQualifications())
                .siteInductions(getSiteInductions());
        builder.email = internalGetEmail();
        builder.phone = internalGetPhone();
        builder.mobile = internalGetMobile();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Personnel}.
     */
    public static class Builder {
        private Integer personnelId;
        private String firstName;
        private String lastName;
        private OptionalNullable<String> email;
        private OptionalNullable<String> phone;
        private OptionalNullable<String> mobile;
        private Organization1 organization;
        private List<PersonnelQualification> qualifications;
        private List<PersonnelSiteInduction> siteInductions;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for personnelId.
         * @param  personnelId  Integer value for personnelId.
         * @return Builder
         */
        public Builder personnelId(Integer personnelId) {
            this.personnelId = personnelId;
            return this;
        }

        /**
         * Setter for firstName.
         * @param  firstName  String value for firstName.
         * @return Builder
         */
        public Builder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * Setter for lastName.
         * @param  lastName  String value for lastName.
         * @return Builder
         */
        public Builder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = OptionalNullable.of(email);
            return this;
        }

        /**
         * UnSetter for email.
         * @return Builder
         */
        public Builder unsetEmail() {
            email = null;
            return this;
        }

        /**
         * Setter for phone.
         * @param  phone  String value for phone.
         * @return Builder
         */
        public Builder phone(String phone) {
            this.phone = OptionalNullable.of(phone);
            return this;
        }

        /**
         * UnSetter for phone.
         * @return Builder
         */
        public Builder unsetPhone() {
            phone = null;
            return this;
        }

        /**
         * Setter for mobile.
         * @param  mobile  String value for mobile.
         * @return Builder
         */
        public Builder mobile(String mobile) {
            this.mobile = OptionalNullable.of(mobile);
            return this;
        }

        /**
         * UnSetter for mobile.
         * @return Builder
         */
        public Builder unsetMobile() {
            mobile = null;
            return this;
        }

        /**
         * Setter for organization.
         * @param  organization  Organization1 value for organization.
         * @return Builder
         */
        public Builder organization(Organization1 organization) {
            this.organization = organization;
            return this;
        }

        /**
         * Setter for qualifications.
         * @param  qualifications  List of PersonnelQualification value for qualifications.
         * @return Builder
         */
        public Builder qualifications(List<PersonnelQualification> qualifications) {
            this.qualifications = qualifications;
            return this;
        }

        /**
         * Setter for siteInductions.
         * @param  siteInductions  List of PersonnelSiteInduction value for siteInductions.
         * @return Builder
         */
        public Builder siteInductions(List<PersonnelSiteInduction> siteInductions) {
            this.siteInductions = siteInductions;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Personnel} object using the set fields.
         * @return {@link Personnel}
         */
        public Personnel build() {
            Personnel model =
                    new Personnel(personnelId, firstName, lastName, email, phone, mobile,
                            organization, qualifications, siteInductions);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
