/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PowerCurveValue type.
 */
public class PowerCurveValue {
    private double windSpeed;
    private double power;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PowerCurveValue() {
    }

    /**
     * Initialization constructor.
     * @param  windSpeed  double value for windSpeed.
     * @param  power  double value for power.
     */
    public PowerCurveValue(
            double windSpeed,
            double power) {
        this.windSpeed = windSpeed;
        this.power = power;
    }

    /**
     * Getter for WindSpeed.
     * Wind speed in m/s
     * @return Returns the double
     */
    @JsonGetter("windSpeed")
    public double getWindSpeed() {
        return windSpeed;
    }

    /**
     * Setter for WindSpeed.
     * Wind speed in m/s
     * @param windSpeed Value for double
     */
    @JsonSetter("windSpeed")
    public void setWindSpeed(double windSpeed) {
        this.windSpeed = windSpeed;
    }

    /**
     * Getter for Power.
     * Power in kW
     * @return Returns the double
     */
    @JsonGetter("power")
    public double getPower() {
        return power;
    }

    /**
     * Setter for Power.
     * Power in kW
     * @param power Value for double
     */
    @JsonSetter("power")
    public void setPower(double power) {
        this.power = power;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PowerCurveValue into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PowerCurveValue [" + "windSpeed=" + windSpeed + ", power=" + power
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PowerCurveValue.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PowerCurveValue.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(windSpeed, power);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PowerCurveValue}.
     */
    public static class Builder {
        private double windSpeed;
        private double power;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  windSpeed  double value for windSpeed.
         * @param  power  double value for power.
         */
        public Builder(double windSpeed, double power) {
            this.windSpeed = windSpeed;
            this.power = power;
        }

        /**
         * Setter for windSpeed.
         * @param  windSpeed  double value for windSpeed.
         * @return Builder
         */
        public Builder windSpeed(double windSpeed) {
            this.windSpeed = windSpeed;
            return this;
        }

        /**
         * Setter for power.
         * @param  power  double value for power.
         * @return Builder
         */
        public Builder power(double power) {
            this.power = power;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PowerCurveValue} object using the set fields.
         * @return {@link PowerCurveValue}
         */
        public PowerCurveValue build() {
            PowerCurveValue model =
                    new PowerCurveValue(windSpeed, power);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
