/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * PredictAction to be used.
 */
public enum PredictAction {
    NONE,

    REPAIR,

    REPLACEMENT,

    ENUM_NONE_AUTORESOLVED;

    private static TreeMap<String, PredictAction> valueMap = new TreeMap<>();
    private String value;

    static {
        NONE.value = "none";
        REPAIR.value = "repair";
        REPLACEMENT.value = "replacement";
        ENUM_NONE_AUTORESOLVED.value = "none - auto-resolved";

        valueMap.put("none", NONE);
        valueMap.put("repair", REPAIR);
        valueMap.put("replacement", REPLACEMENT);
        valueMap.put("none - auto-resolved", ENUM_NONE_AUTORESOLVED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PredictAction constructFromString(String toConvert) throws IOException {
        PredictAction enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PredictAction fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PredictAction values to list of string values.
     * @param toConvert The list of PredictAction values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PredictAction> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PredictAction enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 