/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PredictRecommendation type.
 */
public class PredictRecommendation {
    private String component;
    private String action;
    private Integer confidence;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PredictRecommendation() {
    }

    /**
     * Initialization constructor.
     * @param  component  String value for component.
     * @param  action  String value for action.
     * @param  confidence  Integer value for confidence.
     */
    public PredictRecommendation(
            String component,
            String action,
            Integer confidence) {
        this.component = component;
        this.action = action;
        this.confidence = confidence;
    }

    /**
     * Getter for Component.
     * @return Returns the String
     */
    @JsonGetter("component")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getComponent() {
        return component;
    }

    /**
     * Setter for Component.
     * @param component Value for String
     */
    @JsonSetter("component")
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * Getter for Action.
     * @return Returns the String
     */
    @JsonGetter("action")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAction() {
        return action;
    }

    /**
     * Setter for Action.
     * @param action Value for String
     */
    @JsonSetter("action")
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * Getter for Confidence.
     * @return Returns the Integer
     */
    @JsonGetter("confidence")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getConfidence() {
        return confidence;
    }

    /**
     * Setter for Confidence.
     * @param confidence Value for Integer
     */
    @JsonSetter("confidence")
    public void setConfidence(Integer confidence) {
        this.confidence = confidence;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PredictRecommendation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PredictRecommendation [" + "component=" + component + ", action=" + action
                + ", confidence=" + confidence + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link PredictRecommendation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PredictRecommendation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .component(getComponent())
                .action(getAction())
                .confidence(getConfidence());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PredictRecommendation}.
     */
    public static class Builder {
        private String component;
        private String action;
        private Integer confidence;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for component.
         * @param  component  String value for component.
         * @return Builder
         */
        public Builder component(String component) {
            this.component = component;
            return this;
        }

        /**
         * Setter for action.
         * @param  action  String value for action.
         * @return Builder
         */
        public Builder action(String action) {
            this.action = action;
            return this;
        }

        /**
         * Setter for confidence.
         * @param  confidence  Integer value for confidence.
         * @return Builder
         */
        public Builder confidence(Integer confidence) {
            this.confidence = confidence;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PredictRecommendation} object using the set fields.
         * @return {@link PredictRecommendation}
         */
        public PredictRecommendation build() {
            PredictRecommendation model =
                    new PredictRecommendation(component, action, confidence);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
