/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ProblemDetails type.
 */
public class ProblemDetails {
    private int status;
    private String title;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProblemDetails() {
    }

    /**
     * Initialization constructor.
     * @param  status  int value for status.
     * @param  title  String value for title.
     */
    public ProblemDetails(
            int status,
            String title) {
        this.status = status;
        this.title = title;
    }

    /**
     * Getter for Status.
     * @return Returns the int
     */
    @JsonGetter("status")
    public int getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for int
     */
    @JsonSetter("status")
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProblemDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProblemDetails [" + "status=" + status + ", title=" + title
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProblemDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProblemDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status, title);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProblemDetails}.
     */
    public static class Builder {
        private int status;
        private String title;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  int value for status.
         * @param  title  String value for title.
         */
        public Builder(int status, String title) {
            this.status = status;
            this.title = title;
        }

        /**
         * Setter for status.
         * @param  status  int value for status.
         * @return Builder
         */
        public Builder status(int status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProblemDetails} object using the set fields.
         * @return {@link ProblemDetails}
         */
        public ProblemDetails build() {
            ProblemDetails model =
                    new ProblemDetails(status, title);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
