/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import cloud.greenbyte.intro.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDate;
import java.util.Map;

/**
 * This is a model class for Recurrence type.
 */
public class Recurrence {
    private Integer duration;
    private DurationType durationType;
    private LocalDate dateEnd;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Recurrence() {
    }

    /**
     * Initialization constructor.
     * @param  duration  Integer value for duration.
     * @param  durationType  DurationType value for durationType.
     * @param  dateEnd  LocalDate value for dateEnd.
     */
    public Recurrence(
            Integer duration,
            DurationType durationType,
            LocalDate dateEnd) {
        this.duration = duration;
        this.durationType = durationType;
        this.dateEnd = dateEnd;
    }

    /**
     * Getter for Duration.
     * The interval with which the task repeats.
     * @return Returns the Integer
     */
    @JsonGetter("duration")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDuration() {
        return duration;
    }

    /**
     * Setter for Duration.
     * The interval with which the task repeats.
     * @param duration Value for Integer
     */
    @JsonSetter("duration")
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * Getter for DurationType.
     * @return Returns the DurationType
     */
    @JsonGetter("durationType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public DurationType getDurationType() {
        return durationType;
    }

    /**
     * Setter for DurationType.
     * @param durationType Value for DurationType
     */
    @JsonSetter("durationType")
    public void setDurationType(DurationType durationType) {
        this.durationType = durationType;
    }

    /**
     * Getter for DateEnd.
     * When the recurring task series ends (exclusive). The end date is **not** included in the
     * recurring task series: for example, to have a task series occur until and including the last
     * day of March 2020, set `dateEnd` to "2020-04-01".
     * @return Returns the LocalDate
     */
    @JsonGetter("dateEnd")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getDateEnd() {
        return dateEnd;
    }

    /**
     * Setter for DateEnd.
     * When the recurring task series ends (exclusive). The end date is **not** included in the
     * recurring task series: for example, to have a task series occur until and including the last
     * day of March 2020, set `dateEnd` to "2020-04-01".
     * @param dateEnd Value for LocalDate
     */
    @JsonSetter("dateEnd")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setDateEnd(LocalDate dateEnd) {
        this.dateEnd = dateEnd;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Recurrence into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Recurrence [" + "duration=" + duration + ", durationType=" + durationType
                + ", dateEnd=" + dateEnd + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Recurrence.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Recurrence.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .duration(getDuration())
                .durationType(getDurationType())
                .dateEnd(getDateEnd());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Recurrence}.
     */
    public static class Builder {
        private Integer duration;
        private DurationType durationType;
        private LocalDate dateEnd;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for duration.
         * @param  duration  Integer value for duration.
         * @return Builder
         */
        public Builder duration(Integer duration) {
            this.duration = duration;
            return this;
        }

        /**
         * Setter for durationType.
         * @param  durationType  DurationType value for durationType.
         * @return Builder
         */
        public Builder durationType(DurationType durationType) {
            this.durationType = durationType;
            return this;
        }

        /**
         * Setter for dateEnd.
         * @param  dateEnd  LocalDate value for dateEnd.
         * @return Builder
         */
        public Builder dateEnd(LocalDate dateEnd) {
            this.dateEnd = dateEnd;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Recurrence} object using the set fields.
         * @return {@link Recurrence}
         */
        public Recurrence build() {
            Recurrence model =
                    new Recurrence(duration, durationType, dateEnd);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
