/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Resolution to be used.
 */
public enum Resolution {
    ENUM_5MINUTE,

    ENUM_10MINUTE,

    ENUM_15MINUTE,

    HOURLY,

    DAILY,

    WEEKLY,

    MONTHLY,

    YEARLY,

    INTERVAL,

    DEVICE;

    private static TreeMap<String, Resolution> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_5MINUTE.value = "5minute";
        ENUM_10MINUTE.value = "10minute";
        ENUM_15MINUTE.value = "15minute";
        HOURLY.value = "hourly";
        DAILY.value = "daily";
        WEEKLY.value = "weekly";
        MONTHLY.value = "monthly";
        YEARLY.value = "yearly";
        INTERVAL.value = "interval";
        DEVICE.value = "device";

        valueMap.put("5minute", ENUM_5MINUTE);
        valueMap.put("10minute", ENUM_10MINUTE);
        valueMap.put("15minute", ENUM_15MINUTE);
        valueMap.put("hourly", HOURLY);
        valueMap.put("daily", DAILY);
        valueMap.put("weekly", WEEKLY);
        valueMap.put("monthly", MONTHLY);
        valueMap.put("yearly", YEARLY);
        valueMap.put("interval", INTERVAL);
        valueMap.put("device", DEVICE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Resolution constructFromString(String toConvert) throws IOException {
        Resolution enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Resolution fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Resolution values to list of string values.
     * @param toConvert The list of Resolution values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Resolution> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Resolution enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 