/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import cloud.greenbyte.intro.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for SiteAccessPersonnel type.
 */
public class SiteAccessPersonnel {
    private Integer personnelId;
    private String firstName;
    private String lastName;
    private OptionalNullable<String> company;
    private OptionalNullable<String> phoneNumber;
    private OptionalNullable<String> vehicleRegistration;
    private OptionalNullable<String> comment;
    private LocalDateTime timestampStart;
    private OptionalNullable<LocalDateTime> timestampEnd;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SiteAccessPersonnel() {
    }

    /**
     * Initialization constructor.
     * @param  personnelId  Integer value for personnelId.
     * @param  firstName  String value for firstName.
     * @param  lastName  String value for lastName.
     * @param  company  String value for company.
     * @param  phoneNumber  String value for phoneNumber.
     * @param  vehicleRegistration  String value for vehicleRegistration.
     * @param  comment  String value for comment.
     * @param  timestampStart  LocalDateTime value for timestampStart.
     * @param  timestampEnd  LocalDateTime value for timestampEnd.
     */
    public SiteAccessPersonnel(
            Integer personnelId,
            String firstName,
            String lastName,
            String company,
            String phoneNumber,
            String vehicleRegistration,
            String comment,
            LocalDateTime timestampStart,
            LocalDateTime timestampEnd) {
        this.personnelId = personnelId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.company = OptionalNullable.of(company);
        this.phoneNumber = OptionalNullable.of(phoneNumber);
        this.vehicleRegistration = OptionalNullable.of(vehicleRegistration);
        this.comment = OptionalNullable.of(comment);
        this.timestampStart = timestampStart;
        this.timestampEnd = OptionalNullable.of(timestampEnd);
    }

    /**
     * Initialization constructor.
     * @param  personnelId  Integer value for personnelId.
     * @param  firstName  String value for firstName.
     * @param  lastName  String value for lastName.
     * @param  company  String value for company.
     * @param  phoneNumber  String value for phoneNumber.
     * @param  vehicleRegistration  String value for vehicleRegistration.
     * @param  comment  String value for comment.
     * @param  timestampStart  LocalDateTime value for timestampStart.
     * @param  timestampEnd  LocalDateTime value for timestampEnd.
     */

    protected SiteAccessPersonnel(Integer personnelId, String firstName, String lastName,
            OptionalNullable<String> company, OptionalNullable<String> phoneNumber,
            OptionalNullable<String> vehicleRegistration, OptionalNullable<String> comment,
            LocalDateTime timestampStart, OptionalNullable<LocalDateTime> timestampEnd) {
        this.personnelId = personnelId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.company = company;
        this.phoneNumber = phoneNumber;
        this.vehicleRegistration = vehicleRegistration;
        this.comment = comment;
        this.timestampStart = timestampStart;
        this.timestampEnd = timestampEnd;
    }

    /**
     * Getter for PersonnelId.
     * The id of a person in the personnel list.
     * @return Returns the Integer
     */
    @JsonGetter("personnelId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPersonnelId() {
        return personnelId;
    }

    /**
     * Setter for PersonnelId.
     * The id of a person in the personnel list.
     * @param personnelId Value for Integer
     */
    @JsonSetter("personnelId")
    public void setPersonnelId(Integer personnelId) {
        this.personnelId = personnelId;
    }

    /**
     * Getter for FirstName.
     * @return Returns the String
     */
    @JsonGetter("firstName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFirstName() {
        return firstName;
    }

    /**
     * Setter for FirstName.
     * @param firstName Value for String
     */
    @JsonSetter("firstName")
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for LastName.
     * @return Returns the String
     */
    @JsonGetter("lastName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastName() {
        return lastName;
    }

    /**
     * Setter for LastName.
     * @param lastName Value for String
     */
    @JsonSetter("lastName")
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Internal Getter for Company.
     * @return Returns the Internal String
     */
    @JsonGetter("company")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetCompany() {
        return this.company;
    }

    /**
     * Getter for Company.
     * @return Returns the String
     */
    public String getCompany() {
        return OptionalNullable.getFrom(company);
    }

    /**
     * Setter for Company.
     * @param company Value for String
     */
    @JsonSetter("company")
    public void setCompany(String company) {
        this.company = OptionalNullable.of(company);
    }

    /**
     * UnSetter for Company.
     */
    public void unsetCompany() {
        company = null;
    }

    /**
     * Internal Getter for PhoneNumber.
     * @return Returns the Internal String
     */
    @JsonGetter("phoneNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Getter for PhoneNumber.
     * @return Returns the String
     */
    public String getPhoneNumber() {
        return OptionalNullable.getFrom(phoneNumber);
    }

    /**
     * Setter for PhoneNumber.
     * @param phoneNumber Value for String
     */
    @JsonSetter("phoneNumber")
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = OptionalNullable.of(phoneNumber);
    }

    /**
     * UnSetter for PhoneNumber.
     */
    public void unsetPhoneNumber() {
        phoneNumber = null;
    }

    /**
     * Internal Getter for VehicleRegistration.
     * @return Returns the Internal String
     */
    @JsonGetter("vehicleRegistration")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetVehicleRegistration() {
        return this.vehicleRegistration;
    }

    /**
     * Getter for VehicleRegistration.
     * @return Returns the String
     */
    public String getVehicleRegistration() {
        return OptionalNullable.getFrom(vehicleRegistration);
    }

    /**
     * Setter for VehicleRegistration.
     * @param vehicleRegistration Value for String
     */
    @JsonSetter("vehicleRegistration")
    public void setVehicleRegistration(String vehicleRegistration) {
        this.vehicleRegistration = OptionalNullable.of(vehicleRegistration);
    }

    /**
     * UnSetter for VehicleRegistration.
     */
    public void unsetVehicleRegistration() {
        vehicleRegistration = null;
    }

    /**
     * Internal Getter for Comment.
     * @return Returns the Internal String
     */
    @JsonGetter("comment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetComment() {
        return this.comment;
    }

    /**
     * Getter for Comment.
     * @return Returns the String
     */
    public String getComment() {
        return OptionalNullable.getFrom(comment);
    }

    /**
     * Setter for Comment.
     * @param comment Value for String
     */
    @JsonSetter("comment")
    public void setComment(String comment) {
        this.comment = OptionalNullable.of(comment);
    }

    /**
     * UnSetter for Comment.
     */
    public void unsetComment() {
        comment = null;
    }

    /**
     * Getter for TimestampStart.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestampStart")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestampStart() {
        return timestampStart;
    }

    /**
     * Setter for TimestampStart.
     * @param timestampStart Value for LocalDateTime
     */
    @JsonSetter("timestampStart")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestampStart(LocalDateTime timestampStart) {
        this.timestampStart = timestampStart;
    }

    /**
     * Internal Getter for TimestampEnd.
     * @return Returns the Internal LocalDateTime
     */
    @JsonGetter("timestampEnd")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Rfc8601DateTimeSerializer.class)
    protected OptionalNullable<LocalDateTime> internalGetTimestampEnd() {
        return this.timestampEnd;
    }

    /**
     * Getter for TimestampEnd.
     * @return Returns the LocalDateTime
     */
    public LocalDateTime getTimestampEnd() {
        return OptionalNullable.getFrom(timestampEnd);
    }

    /**
     * Setter for TimestampEnd.
     * @param timestampEnd Value for LocalDateTime
     */
    @JsonSetter("timestampEnd")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestampEnd(LocalDateTime timestampEnd) {
        this.timestampEnd = OptionalNullable.of(timestampEnd);
    }

    /**
     * UnSetter for TimestampEnd.
     */
    public void unsetTimestampEnd() {
        timestampEnd = null;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SiteAccessPersonnel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SiteAccessPersonnel [" + "personnelId=" + personnelId + ", firstName=" + firstName
                + ", lastName=" + lastName + ", company=" + company + ", phoneNumber=" + phoneNumber
                + ", vehicleRegistration=" + vehicleRegistration + ", comment=" + comment
                + ", timestampStart=" + timestampStart + ", timestampEnd=" + timestampEnd
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SiteAccessPersonnel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SiteAccessPersonnel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .personnelId(getPersonnelId())
                .firstName(getFirstName())
                .lastName(getLastName())
                .timestampStart(getTimestampStart());
        builder.company = internalGetCompany();
        builder.phoneNumber = internalGetPhoneNumber();
        builder.vehicleRegistration = internalGetVehicleRegistration();
        builder.comment = internalGetComment();
        builder.timestampEnd = internalGetTimestampEnd();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SiteAccessPersonnel}.
     */
    public static class Builder {
        private Integer personnelId;
        private String firstName;
        private String lastName;
        private OptionalNullable<String> company;
        private OptionalNullable<String> phoneNumber;
        private OptionalNullable<String> vehicleRegistration;
        private OptionalNullable<String> comment;
        private LocalDateTime timestampStart;
        private OptionalNullable<LocalDateTime> timestampEnd;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for personnelId.
         * @param  personnelId  Integer value for personnelId.
         * @return Builder
         */
        public Builder personnelId(Integer personnelId) {
            this.personnelId = personnelId;
            return this;
        }

        /**
         * Setter for firstName.
         * @param  firstName  String value for firstName.
         * @return Builder
         */
        public Builder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * Setter for lastName.
         * @param  lastName  String value for lastName.
         * @return Builder
         */
        public Builder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * Setter for company.
         * @param  company  String value for company.
         * @return Builder
         */
        public Builder company(String company) {
            this.company = OptionalNullable.of(company);
            return this;
        }

        /**
         * UnSetter for company.
         * @return Builder
         */
        public Builder unsetCompany() {
            company = null;
            return this;
        }

        /**
         * Setter for phoneNumber.
         * @param  phoneNumber  String value for phoneNumber.
         * @return Builder
         */
        public Builder phoneNumber(String phoneNumber) {
            this.phoneNumber = OptionalNullable.of(phoneNumber);
            return this;
        }

        /**
         * UnSetter for phoneNumber.
         * @return Builder
         */
        public Builder unsetPhoneNumber() {
            phoneNumber = null;
            return this;
        }

        /**
         * Setter for vehicleRegistration.
         * @param  vehicleRegistration  String value for vehicleRegistration.
         * @return Builder
         */
        public Builder vehicleRegistration(String vehicleRegistration) {
            this.vehicleRegistration = OptionalNullable.of(vehicleRegistration);
            return this;
        }

        /**
         * UnSetter for vehicleRegistration.
         * @return Builder
         */
        public Builder unsetVehicleRegistration() {
            vehicleRegistration = null;
            return this;
        }

        /**
         * Setter for comment.
         * @param  comment  String value for comment.
         * @return Builder
         */
        public Builder comment(String comment) {
            this.comment = OptionalNullable.of(comment);
            return this;
        }

        /**
         * UnSetter for comment.
         * @return Builder
         */
        public Builder unsetComment() {
            comment = null;
            return this;
        }

        /**
         * Setter for timestampStart.
         * @param  timestampStart  LocalDateTime value for timestampStart.
         * @return Builder
         */
        public Builder timestampStart(LocalDateTime timestampStart) {
            this.timestampStart = timestampStart;
            return this;
        }

        /**
         * Setter for timestampEnd.
         * @param  timestampEnd  LocalDateTime value for timestampEnd.
         * @return Builder
         */
        public Builder timestampEnd(LocalDateTime timestampEnd) {
            this.timestampEnd = OptionalNullable.of(timestampEnd);
            return this;
        }

        /**
         * UnSetter for timestampEnd.
         * @return Builder
         */
        public Builder unsetTimestampEnd() {
            timestampEnd = null;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SiteAccessPersonnel} object using the set fields.
         * @return {@link SiteAccessPersonnel}
         */
        public SiteAccessPersonnel build() {
            SiteAccessPersonnel model =
                    new SiteAccessPersonnel(personnelId, firstName, lastName, company, phoneNumber,
                            vehicleRegistration, comment, timestampStart, timestampEnd);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
