/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import cloud.greenbyte.intro.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for StatusItem type.
 */
public class StatusItem {
    private Integer turbineStatusId;
    private Integer deviceId;
    private LocalDateTime timestampStart;
    private LocalDateTime timestampEnd;
    private Boolean hasTimestampEnd;
    private StatusCategory category;
    private Integer code;
    private String message;
    private OptionalNullable<String> comment;
    private LostProductionSignal lostProductionSignal;
    private Double lostProduction;
    private String categoryIec;
    private String categoryContract;
    private OptionalNullable<String> categoryGlobalContract;
    private OptionalNullable<String> categoryCustomContract;
    private OptionalNullable<List<StatusItem>> subStatus;
    private Boolean acknowledged;
    private Object component;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public StatusItem() {
    }

    /**
     * Initialization constructor.
     * @param  turbineStatusId  Integer value for turbineStatusId.
     * @param  deviceId  Integer value for deviceId.
     * @param  timestampStart  LocalDateTime value for timestampStart.
     * @param  timestampEnd  LocalDateTime value for timestampEnd.
     * @param  hasTimestampEnd  Boolean value for hasTimestampEnd.
     * @param  category  StatusCategory value for category.
     * @param  code  Integer value for code.
     * @param  message  String value for message.
     * @param  comment  String value for comment.
     * @param  lostProductionSignal  LostProductionSignal value for lostProductionSignal.
     * @param  lostProduction  Double value for lostProduction.
     * @param  categoryIec  String value for categoryIec.
     * @param  categoryContract  String value for categoryContract.
     * @param  categoryGlobalContract  String value for categoryGlobalContract.
     * @param  categoryCustomContract  String value for categoryCustomContract.
     * @param  subStatus  List of StatusItem value for subStatus.
     * @param  acknowledged  Boolean value for acknowledged.
     * @param  component  Object value for component.
     */
    public StatusItem(
            Integer turbineStatusId,
            Integer deviceId,
            LocalDateTime timestampStart,
            LocalDateTime timestampEnd,
            Boolean hasTimestampEnd,
            StatusCategory category,
            Integer code,
            String message,
            String comment,
            LostProductionSignal lostProductionSignal,
            Double lostProduction,
            String categoryIec,
            String categoryContract,
            String categoryGlobalContract,
            String categoryCustomContract,
            List<StatusItem> subStatus,
            Boolean acknowledged,
            Object component) {
        this.turbineStatusId = turbineStatusId;
        this.deviceId = deviceId;
        this.timestampStart = timestampStart;
        this.timestampEnd = timestampEnd;
        this.hasTimestampEnd = hasTimestampEnd;
        this.category = category;
        this.code = code;
        this.message = message;
        this.comment = OptionalNullable.of(comment);
        this.lostProductionSignal = lostProductionSignal;
        this.lostProduction = lostProduction;
        this.categoryIec = categoryIec;
        this.categoryContract = categoryContract;
        this.categoryGlobalContract = OptionalNullable.of(categoryGlobalContract);
        this.categoryCustomContract = OptionalNullable.of(categoryCustomContract);
        this.subStatus = OptionalNullable.of(subStatus);
        this.acknowledged = acknowledged;
        this.component = component;
    }

    /**
     * Initialization constructor.
     * @param  turbineStatusId  Integer value for turbineStatusId.
     * @param  deviceId  Integer value for deviceId.
     * @param  timestampStart  LocalDateTime value for timestampStart.
     * @param  timestampEnd  LocalDateTime value for timestampEnd.
     * @param  hasTimestampEnd  Boolean value for hasTimestampEnd.
     * @param  category  StatusCategory value for category.
     * @param  code  Integer value for code.
     * @param  message  String value for message.
     * @param  comment  String value for comment.
     * @param  lostProductionSignal  LostProductionSignal value for lostProductionSignal.
     * @param  lostProduction  Double value for lostProduction.
     * @param  categoryIec  String value for categoryIec.
     * @param  categoryContract  String value for categoryContract.
     * @param  categoryGlobalContract  String value for categoryGlobalContract.
     * @param  categoryCustomContract  String value for categoryCustomContract.
     * @param  subStatus  List of StatusItem value for subStatus.
     * @param  acknowledged  Boolean value for acknowledged.
     * @param  component  Object value for component.
     */

    protected StatusItem(Integer turbineStatusId, Integer deviceId, LocalDateTime timestampStart,
            LocalDateTime timestampEnd, Boolean hasTimestampEnd, StatusCategory category,
            Integer code, String message, OptionalNullable<String> comment,
            LostProductionSignal lostProductionSignal, Double lostProduction, String categoryIec,
            String categoryContract, OptionalNullable<String> categoryGlobalContract,
            OptionalNullable<String> categoryCustomContract,
            OptionalNullable<List<StatusItem>> subStatus, Boolean acknowledged,
            Object component) {
        this.turbineStatusId = turbineStatusId;
        this.deviceId = deviceId;
        this.timestampStart = timestampStart;
        this.timestampEnd = timestampEnd;
        this.hasTimestampEnd = hasTimestampEnd;
        this.category = category;
        this.code = code;
        this.message = message;
        this.comment = comment;
        this.lostProductionSignal = lostProductionSignal;
        this.lostProduction = lostProduction;
        this.categoryIec = categoryIec;
        this.categoryContract = categoryContract;
        this.categoryGlobalContract = categoryGlobalContract;
        this.categoryCustomContract = categoryCustomContract;
        this.subStatus = subStatus;
        this.acknowledged = acknowledged;
        this.component = component;
    }

    /**
     * Getter for TurbineStatusId.
     * The id of a turbine status.
     * @return Returns the Integer
     */
    @JsonGetter("turbineStatusId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTurbineStatusId() {
        return turbineStatusId;
    }

    /**
     * Setter for TurbineStatusId.
     * The id of a turbine status.
     * @param turbineStatusId Value for Integer
     */
    @JsonSetter("turbineStatusId")
    public void setTurbineStatusId(Integer turbineStatusId) {
        this.turbineStatusId = turbineStatusId;
    }

    /**
     * Getter for DeviceId.
     * The id of a device.
     * @return Returns the Integer
     */
    @JsonGetter("deviceId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * Setter for DeviceId.
     * The id of a device.
     * @param deviceId Value for Integer
     */
    @JsonSetter("deviceId")
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Getter for TimestampStart.
     * The timestamp when the status began. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestampStart")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestampStart() {
        return timestampStart;
    }

    /**
     * Setter for TimestampStart.
     * The timestamp when the status began. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @param timestampStart Value for LocalDateTime
     */
    @JsonSetter("timestampStart")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestampStart(LocalDateTime timestampStart) {
        this.timestampStart = timestampStart;
    }

    /**
     * Getter for TimestampEnd.
     * The timestamp when the status ended. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestampEnd")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestampEnd() {
        return timestampEnd;
    }

    /**
     * Setter for TimestampEnd.
     * The timestamp when the status ended. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @param timestampEnd Value for LocalDateTime
     */
    @JsonSetter("timestampEnd")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestampEnd(LocalDateTime timestampEnd) {
        this.timestampEnd = timestampEnd;
    }

    /**
     * Getter for HasTimestampEnd.
     * Indicates whether the status has a duration.
     * @return Returns the Boolean
     */
    @JsonGetter("hasTimestampEnd")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getHasTimestampEnd() {
        return hasTimestampEnd;
    }

    /**
     * Setter for HasTimestampEnd.
     * Indicates whether the status has a duration.
     * @param hasTimestampEnd Value for Boolean
     */
    @JsonSetter("hasTimestampEnd")
    public void setHasTimestampEnd(Boolean hasTimestampEnd) {
        this.hasTimestampEnd = hasTimestampEnd;
    }

    /**
     * Getter for Category.
     * @return Returns the StatusCategory
     */
    @JsonGetter("category")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public StatusCategory getCategory() {
        return category;
    }

    /**
     * Setter for Category.
     * @param category Value for StatusCategory
     */
    @JsonSetter("category")
    public void setCategory(StatusCategory category) {
        this.category = category;
    }

    /**
     * Getter for Code.
     * The status code.
     * @return Returns the Integer
     */
    @JsonGetter("code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * The status code.
     * @param code Value for Integer
     */
    @JsonSetter("code")
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * Getter for Message.
     * A description of the status code.
     * @return Returns the String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * A description of the status code.
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Internal Getter for Comment.
     * A user comment associated with the status.
     * @return Returns the Internal String
     */
    @JsonGetter("comment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetComment() {
        return this.comment;
    }

    /**
     * Getter for Comment.
     * A user comment associated with the status.
     * @return Returns the String
     */
    public String getComment() {
        return OptionalNullable.getFrom(comment);
    }

    /**
     * Setter for Comment.
     * A user comment associated with the status.
     * @param comment Value for String
     */
    @JsonSetter("comment")
    public void setComment(String comment) {
        this.comment = OptionalNullable.of(comment);
    }

    /**
     * UnSetter for Comment.
     * A user comment associated with the status.
     */
    public void unsetComment() {
        comment = null;
    }

    /**
     * Getter for LostProductionSignal.
     * @return Returns the LostProductionSignal
     */
    @JsonGetter("lostProductionSignal")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public LostProductionSignal getLostProductionSignal() {
        return lostProductionSignal;
    }

    /**
     * Setter for LostProductionSignal.
     * @param lostProductionSignal Value for LostProductionSignal
     */
    @JsonSetter("lostProductionSignal")
    public void setLostProductionSignal(LostProductionSignal lostProductionSignal) {
        this.lostProductionSignal = lostProductionSignal;
    }

    /**
     * Getter for LostProduction.
     * The lost production in kWh associated with the status. This field will be null if the caller
     * is not authorized for the system-configured lost production signal. The configured lost
     * production signal is available via the `/configuration.json` endpoint
     * (`DataSignalConfiguration` schema).
     * @return Returns the Double
     */
    @JsonGetter("lostProduction")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getLostProduction() {
        return lostProduction;
    }

    /**
     * Setter for LostProduction.
     * The lost production in kWh associated with the status. This field will be null if the caller
     * is not authorized for the system-configured lost production signal. The configured lost
     * production signal is available via the `/configuration.json` endpoint
     * (`DataSignalConfiguration` schema).
     * @param lostProduction Value for Double
     */
    @JsonSetter("lostProduction")
    public void setLostProduction(Double lostProduction) {
        this.lostProduction = lostProduction;
    }

    /**
     * Getter for CategoryIec.
     * The status category as defined by the IEC.
     * @return Returns the String
     */
    @JsonGetter("categoryIec")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCategoryIec() {
        return categoryIec;
    }

    /**
     * Setter for CategoryIec.
     * The status category as defined by the IEC.
     * @param categoryIec Value for String
     */
    @JsonSetter("categoryIec")
    public void setCategoryIec(String categoryIec) {
        this.categoryIec = categoryIec;
    }

    /**
     * Getter for CategoryContract.
     * The status category as defined in the service availability contract assigned to the site.
     * @return Returns the String
     */
    @JsonGetter("categoryContract")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCategoryContract() {
        return categoryContract;
    }

    /**
     * Setter for CategoryContract.
     * The status category as defined in the service availability contract assigned to the site.
     * @param categoryContract Value for String
     */
    @JsonSetter("categoryContract")
    public void setCategoryContract(String categoryContract) {
        this.categoryContract = categoryContract;
    }

    /**
     * Internal Getter for CategoryGlobalContract.
     * The status category as defined in the global availability contract assigned to the site.
     * @return Returns the Internal String
     */
    @JsonGetter("categoryGlobalContract")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetCategoryGlobalContract() {
        return this.categoryGlobalContract;
    }

    /**
     * Getter for CategoryGlobalContract.
     * The status category as defined in the global availability contract assigned to the site.
     * @return Returns the String
     */
    public String getCategoryGlobalContract() {
        return OptionalNullable.getFrom(categoryGlobalContract);
    }

    /**
     * Setter for CategoryGlobalContract.
     * The status category as defined in the global availability contract assigned to the site.
     * @param categoryGlobalContract Value for String
     */
    @JsonSetter("categoryGlobalContract")
    public void setCategoryGlobalContract(String categoryGlobalContract) {
        this.categoryGlobalContract = OptionalNullable.of(categoryGlobalContract);
    }

    /**
     * UnSetter for CategoryGlobalContract.
     * The status category as defined in the global availability contract assigned to the site.
     */
    public void unsetCategoryGlobalContract() {
        categoryGlobalContract = null;
    }

    /**
     * Internal Getter for CategoryCustomContract.
     * The status category as defined in the custom availability contract assigned to the site.
     * @return Returns the Internal String
     */
    @JsonGetter("categoryCustomContract")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetCategoryCustomContract() {
        return this.categoryCustomContract;
    }

    /**
     * Getter for CategoryCustomContract.
     * The status category as defined in the custom availability contract assigned to the site.
     * @return Returns the String
     */
    public String getCategoryCustomContract() {
        return OptionalNullable.getFrom(categoryCustomContract);
    }

    /**
     * Setter for CategoryCustomContract.
     * The status category as defined in the custom availability contract assigned to the site.
     * @param categoryCustomContract Value for String
     */
    @JsonSetter("categoryCustomContract")
    public void setCategoryCustomContract(String categoryCustomContract) {
        this.categoryCustomContract = OptionalNullable.of(categoryCustomContract);
    }

    /**
     * UnSetter for CategoryCustomContract.
     * The status category as defined in the custom availability contract assigned to the site.
     */
    public void unsetCategoryCustomContract() {
        categoryCustomContract = null;
    }

    /**
     * Internal Getter for SubStatus.
     * Statuses of the same type that have been grouped under this status.
     * @return Returns the Internal List of StatusItem
     */
    @JsonGetter("subStatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<List<StatusItem>> internalGetSubStatus() {
        return this.subStatus;
    }

    /**
     * Getter for SubStatus.
     * Statuses of the same type that have been grouped under this status.
     * @return Returns the List of StatusItem
     */
    public List<StatusItem> getSubStatus() {
        return OptionalNullable.getFrom(subStatus);
    }

    /**
     * Setter for SubStatus.
     * Statuses of the same type that have been grouped under this status.
     * @param subStatus Value for List of StatusItem
     */
    @JsonSetter("subStatus")
    public void setSubStatus(List<StatusItem> subStatus) {
        this.subStatus = OptionalNullable.of(subStatus);
    }

    /**
     * UnSetter for SubStatus.
     * Statuses of the same type that have been grouped under this status.
     */
    public void unsetSubStatus() {
        subStatus = null;
    }

    /**
     * Getter for Acknowledged.
     * Indicates whether the status has been acknowledged.
     * @return Returns the Boolean
     */
    @JsonGetter("acknowledged")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getAcknowledged() {
        return acknowledged;
    }

    /**
     * Setter for Acknowledged.
     * Indicates whether the status has been acknowledged.
     * @param acknowledged Value for Boolean
     */
    @JsonSetter("acknowledged")
    public void setAcknowledged(Boolean acknowledged) {
        this.acknowledged = acknowledged;
    }

    /**
     * Getter for Component.
     * The status component categorization.
     * @return Returns the Object
     */
    @JsonGetter("component")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getComponent() {
        return component;
    }

    /**
     * Setter for Component.
     * The status component categorization.
     * @param component Value for Object
     */
    @JsonSetter("component")
    public void setComponent(Object component) {
        this.component = component;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this StatusItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "StatusItem [" + "turbineStatusId=" + turbineStatusId + ", deviceId=" + deviceId
                + ", timestampStart=" + timestampStart + ", timestampEnd=" + timestampEnd
                + ", hasTimestampEnd=" + hasTimestampEnd + ", category=" + category + ", code="
                + code + ", message=" + message + ", comment=" + comment + ", lostProductionSignal="
                + lostProductionSignal + ", lostProduction=" + lostProduction + ", categoryIec="
                + categoryIec + ", categoryContract=" + categoryContract
                + ", categoryGlobalContract=" + categoryGlobalContract + ", categoryCustomContract="
                + categoryCustomContract + ", subStatus=" + subStatus + ", acknowledged="
                + acknowledged + ", component=" + component + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link StatusItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link StatusItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .turbineStatusId(getTurbineStatusId())
                .deviceId(getDeviceId())
                .timestampStart(getTimestampStart())
                .timestampEnd(getTimestampEnd())
                .hasTimestampEnd(getHasTimestampEnd())
                .category(getCategory())
                .code(getCode())
                .message(getMessage())
                .lostProductionSignal(getLostProductionSignal())
                .lostProduction(getLostProduction())
                .categoryIec(getCategoryIec())
                .categoryContract(getCategoryContract())
                .acknowledged(getAcknowledged())
                .component(getComponent());
        builder.comment = internalGetComment();
        builder.categoryGlobalContract = internalGetCategoryGlobalContract();
        builder.categoryCustomContract = internalGetCategoryCustomContract();
        builder.subStatus = internalGetSubStatus();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link StatusItem}.
     */
    public static class Builder {
        private Integer turbineStatusId;
        private Integer deviceId;
        private LocalDateTime timestampStart;
        private LocalDateTime timestampEnd;
        private Boolean hasTimestampEnd;
        private StatusCategory category;
        private Integer code;
        private String message;
        private OptionalNullable<String> comment;
        private LostProductionSignal lostProductionSignal;
        private Double lostProduction;
        private String categoryIec;
        private String categoryContract;
        private OptionalNullable<String> categoryGlobalContract;
        private OptionalNullable<String> categoryCustomContract;
        private OptionalNullable<List<StatusItem>> subStatus;
        private Boolean acknowledged;
        private Object component;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for turbineStatusId.
         * @param  turbineStatusId  Integer value for turbineStatusId.
         * @return Builder
         */
        public Builder turbineStatusId(Integer turbineStatusId) {
            this.turbineStatusId = turbineStatusId;
            return this;
        }

        /**
         * Setter for deviceId.
         * @param  deviceId  Integer value for deviceId.
         * @return Builder
         */
        public Builder deviceId(Integer deviceId) {
            this.deviceId = deviceId;
            return this;
        }

        /**
         * Setter for timestampStart.
         * @param  timestampStart  LocalDateTime value for timestampStart.
         * @return Builder
         */
        public Builder timestampStart(LocalDateTime timestampStart) {
            this.timestampStart = timestampStart;
            return this;
        }

        /**
         * Setter for timestampEnd.
         * @param  timestampEnd  LocalDateTime value for timestampEnd.
         * @return Builder
         */
        public Builder timestampEnd(LocalDateTime timestampEnd) {
            this.timestampEnd = timestampEnd;
            return this;
        }

        /**
         * Setter for hasTimestampEnd.
         * @param  hasTimestampEnd  Boolean value for hasTimestampEnd.
         * @return Builder
         */
        public Builder hasTimestampEnd(Boolean hasTimestampEnd) {
            this.hasTimestampEnd = hasTimestampEnd;
            return this;
        }

        /**
         * Setter for category.
         * @param  category  StatusCategory value for category.
         * @return Builder
         */
        public Builder category(StatusCategory category) {
            this.category = category;
            return this;
        }

        /**
         * Setter for code.
         * @param  code  Integer value for code.
         * @return Builder
         */
        public Builder code(Integer code) {
            this.code = code;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for comment.
         * @param  comment  String value for comment.
         * @return Builder
         */
        public Builder comment(String comment) {
            this.comment = OptionalNullable.of(comment);
            return this;
        }

        /**
         * UnSetter for comment.
         * @return Builder
         */
        public Builder unsetComment() {
            comment = null;
            return this;
        }

        /**
         * Setter for lostProductionSignal.
         * @param  lostProductionSignal  LostProductionSignal value for lostProductionSignal.
         * @return Builder
         */
        public Builder lostProductionSignal(LostProductionSignal lostProductionSignal) {
            this.lostProductionSignal = lostProductionSignal;
            return this;
        }

        /**
         * Setter for lostProduction.
         * @param  lostProduction  Double value for lostProduction.
         * @return Builder
         */
        public Builder lostProduction(Double lostProduction) {
            this.lostProduction = lostProduction;
            return this;
        }

        /**
         * Setter for categoryIec.
         * @param  categoryIec  String value for categoryIec.
         * @return Builder
         */
        public Builder categoryIec(String categoryIec) {
            this.categoryIec = categoryIec;
            return this;
        }

        /**
         * Setter for categoryContract.
         * @param  categoryContract  String value for categoryContract.
         * @return Builder
         */
        public Builder categoryContract(String categoryContract) {
            this.categoryContract = categoryContract;
            return this;
        }

        /**
         * Setter for categoryGlobalContract.
         * @param  categoryGlobalContract  String value for categoryGlobalContract.
         * @return Builder
         */
        public Builder categoryGlobalContract(String categoryGlobalContract) {
            this.categoryGlobalContract = OptionalNullable.of(categoryGlobalContract);
            return this;
        }

        /**
         * UnSetter for categoryGlobalContract.
         * @return Builder
         */
        public Builder unsetCategoryGlobalContract() {
            categoryGlobalContract = null;
            return this;
        }

        /**
         * Setter for categoryCustomContract.
         * @param  categoryCustomContract  String value for categoryCustomContract.
         * @return Builder
         */
        public Builder categoryCustomContract(String categoryCustomContract) {
            this.categoryCustomContract = OptionalNullable.of(categoryCustomContract);
            return this;
        }

        /**
         * UnSetter for categoryCustomContract.
         * @return Builder
         */
        public Builder unsetCategoryCustomContract() {
            categoryCustomContract = null;
            return this;
        }

        /**
         * Setter for subStatus.
         * @param  subStatus  List of StatusItem value for subStatus.
         * @return Builder
         */
        public Builder subStatus(List<StatusItem> subStatus) {
            this.subStatus = OptionalNullable.of(subStatus);
            return this;
        }

        /**
         * UnSetter for subStatus.
         * @return Builder
         */
        public Builder unsetSubStatus() {
            subStatus = null;
            return this;
        }

        /**
         * Setter for acknowledged.
         * @param  acknowledged  Boolean value for acknowledged.
         * @return Builder
         */
        public Builder acknowledged(Boolean acknowledged) {
            this.acknowledged = acknowledged;
            return this;
        }

        /**
         * Setter for component.
         * @param  component  Object value for component.
         * @return Builder
         */
        public Builder component(Object component) {
            this.component = component;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link StatusItem} object using the set fields.
         * @return {@link StatusItem}
         */
        public StatusItem build() {
            StatusItem model =
                    new StatusItem(turbineStatusId, deviceId, timestampStart, timestampEnd,
                            hasTimestampEnd, category, code, message, comment, lostProductionSignal,
                            lostProduction, categoryIec, categoryContract, categoryGlobalContract,
                            categoryCustomContract, subStatus, acknowledged, component);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
