/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * TaskPriority to be used.
 */
public enum TaskPriority {
    LOW,

    MEDIUM,

    HIGH;

    private static TreeMap<String, TaskPriority> valueMap = new TreeMap<>();
    private String value;

    static {
        LOW.value = "low";
        MEDIUM.value = "medium";
        HIGH.value = "high";

        valueMap.put("low", LOW);
        valueMap.put("medium", MEDIUM);
        valueMap.put("high", HIGH);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static TaskPriority constructFromString(String toConvert) throws IOException {
        TaskPriority enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static TaskPriority fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TaskPriority values to list of string values.
     * @param toConvert The list of TaskPriority values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<TaskPriority> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (TaskPriority enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 