/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for TaskAssigneeUser type.
 */
public class TaskAssigneeUser {
    private String firstName;
    private String lastName;
    private TaskAssigneeType assigneeType;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public TaskAssigneeUser() {
    }

    /**
     * Initialization constructor.
     * @param  firstName  String value for firstName.
     * @param  lastName  String value for lastName.
     * @param  assigneeType  TaskAssigneeType value for assigneeType.
     */
    @JsonCreator
    public TaskAssigneeUser(
            @JsonProperty("firstName") String firstName,
            @JsonProperty("lastName") String lastName,
            @JsonProperty("assigneeType") TaskAssigneeType assigneeType) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.assigneeType = assigneeType;
    }

    /**
     * Getter for FirstName.
     * @return Returns the String
     */
    @JsonGetter("firstName")
    public String getFirstName() {
        return firstName;
    }

    /**
     * Setter for FirstName.
     * @param firstName Value for String
     */
    @JsonSetter("firstName")
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for LastName.
     * @return Returns the String
     */
    @JsonGetter("lastName")
    public String getLastName() {
        return lastName;
    }

    /**
     * Setter for LastName.
     * @param lastName Value for String
     */
    @JsonSetter("lastName")
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for AssigneeType.
     * @return Returns the TaskAssigneeType
     */
    @JsonGetter("assigneeType")
    public TaskAssigneeType getAssigneeType() {
        return assigneeType;
    }

    /**
     * Setter for AssigneeType.
     * @param assigneeType Value for TaskAssigneeType
     */
    @JsonSetter("assigneeType")
    public void setAssigneeType(TaskAssigneeType assigneeType) {
        this.assigneeType = assigneeType;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this TaskAssigneeUser into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TaskAssigneeUser [" + "firstName=" + firstName + ", lastName=" + lastName
                + ", assigneeType=" + assigneeType + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link TaskAssigneeUser.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TaskAssigneeUser.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(firstName, lastName, assigneeType);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link TaskAssigneeUser}.
     */
    public static class Builder {
        private String firstName;
        private String lastName;
        private TaskAssigneeType assigneeType;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  firstName  String value for firstName.
         * @param  lastName  String value for lastName.
         * @param  assigneeType  TaskAssigneeType value for assigneeType.
         */
        public Builder(String firstName, String lastName, TaskAssigneeType assigneeType) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.assigneeType = assigneeType;
        }

        /**
         * Setter for firstName.
         * @param  firstName  String value for firstName.
         * @return Builder
         */
        public Builder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * Setter for lastName.
         * @param  lastName  String value for lastName.
         * @return Builder
         */
        public Builder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * Setter for assigneeType.
         * @param  assigneeType  TaskAssigneeType value for assigneeType.
         * @return Builder
         */
        public Builder assigneeType(TaskAssigneeType assigneeType) {
            this.assigneeType = assigneeType;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link TaskAssigneeUser} object using the set fields.
         * @return {@link TaskAssigneeUser}
         */
        public TaskAssigneeUser build() {
            TaskAssigneeUser model =
                    new TaskAssigneeUser(firstName, lastName, assigneeType);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
