/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import cloud.greenbyte.intro.DateTimeHelper;
import cloud.greenbyte.intro.models.containers.TasksResponseAssignee;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for TasksResponse type.
 */
public class TasksResponse {
    private int taskId;
    private String title;
    private User createdBy;
    private OptionalNullable<String> description;
    private Category category;
    private TaskPriority priority;
    private LocalDateTime timestampStart;
    private LocalDateTime timestampEnd;
    private TaskState state;
    private boolean resolved;
    private OptionalNullable<LocalDateTime> timestampResolved;
    private List<Integer> deviceIds;
    private List<Integer> siteIds;
    private List<Integer> siteAccessIds;
    private List<Integer> downtimeEventIds;
    private List<Integer> statusIds;
    private int numberOfComments;
    private List<TaskComment> comments;
    private Object recurrence;
    private OptionalNullable<Integer> mainTaskId;
    private TasksResponseAssignee assignee;
    private List<MetadataField> metadata;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public TasksResponse() {
    }

    /**
     * Initialization constructor.
     * @param  taskId  int value for taskId.
     * @param  title  String value for title.
     * @param  createdBy  User value for createdBy.
     * @param  priority  TaskPriority value for priority.
     * @param  timestampStart  LocalDateTime value for timestampStart.
     * @param  timestampEnd  LocalDateTime value for timestampEnd.
     * @param  state  TaskState value for state.
     * @param  resolved  boolean value for resolved.
     * @param  numberOfComments  int value for numberOfComments.
     * @param  description  String value for description.
     * @param  category  Category value for category.
     * @param  timestampResolved  LocalDateTime value for timestampResolved.
     * @param  deviceIds  List of Integer value for deviceIds.
     * @param  siteIds  List of Integer value for siteIds.
     * @param  siteAccessIds  List of Integer value for siteAccessIds.
     * @param  downtimeEventIds  List of Integer value for downtimeEventIds.
     * @param  statusIds  List of Integer value for statusIds.
     * @param  comments  List of TaskComment value for comments.
     * @param  recurrence  Object value for recurrence.
     * @param  mainTaskId  Integer value for mainTaskId.
     * @param  assignee  TasksResponseAssignee value for assignee.
     * @param  metadata  List of MetadataField value for metadata.
     */
    public TasksResponse(
            int taskId,
            String title,
            User createdBy,
            TaskPriority priority,
            LocalDateTime timestampStart,
            LocalDateTime timestampEnd,
            TaskState state,
            boolean resolved,
            int numberOfComments,
            String description,
            Category category,
            LocalDateTime timestampResolved,
            List<Integer> deviceIds,
            List<Integer> siteIds,
            List<Integer> siteAccessIds,
            List<Integer> downtimeEventIds,
            List<Integer> statusIds,
            List<TaskComment> comments,
            Object recurrence,
            Integer mainTaskId,
            TasksResponseAssignee assignee,
            List<MetadataField> metadata) {
        this.taskId = taskId;
        this.title = title;
        this.createdBy = createdBy;
        this.description = OptionalNullable.of(description);
        this.category = category;
        this.priority = priority;
        this.timestampStart = timestampStart;
        this.timestampEnd = timestampEnd;
        this.state = state;
        this.resolved = resolved;
        this.timestampResolved = OptionalNullable.of(timestampResolved);
        this.deviceIds = deviceIds;
        this.siteIds = siteIds;
        this.siteAccessIds = siteAccessIds;
        this.downtimeEventIds = downtimeEventIds;
        this.statusIds = statusIds;
        this.numberOfComments = numberOfComments;
        this.comments = comments;
        this.recurrence = recurrence;
        this.mainTaskId = OptionalNullable.of(mainTaskId);
        this.assignee = assignee;
        this.metadata = metadata;
    }

    /**
     * Initialization constructor.
     * @param  taskId  int value for taskId.
     * @param  title  String value for title.
     * @param  createdBy  User value for createdBy.
     * @param  priority  TaskPriority value for priority.
     * @param  timestampStart  LocalDateTime value for timestampStart.
     * @param  timestampEnd  LocalDateTime value for timestampEnd.
     * @param  state  TaskState value for state.
     * @param  resolved  boolean value for resolved.
     * @param  numberOfComments  int value for numberOfComments.
     * @param  description  String value for description.
     * @param  category  Category value for category.
     * @param  timestampResolved  LocalDateTime value for timestampResolved.
     * @param  deviceIds  List of Integer value for deviceIds.
     * @param  siteIds  List of Integer value for siteIds.
     * @param  siteAccessIds  List of Integer value for siteAccessIds.
     * @param  downtimeEventIds  List of Integer value for downtimeEventIds.
     * @param  statusIds  List of Integer value for statusIds.
     * @param  comments  List of TaskComment value for comments.
     * @param  recurrence  Object value for recurrence.
     * @param  mainTaskId  Integer value for mainTaskId.
     * @param  assignee  TasksResponseAssignee value for assignee.
     * @param  metadata  List of MetadataField value for metadata.
     */

    protected TasksResponse(int taskId, String title, User createdBy, TaskPriority priority,
            LocalDateTime timestampStart, LocalDateTime timestampEnd, TaskState state,
            boolean resolved, int numberOfComments, OptionalNullable<String> description,
            Category category, OptionalNullable<LocalDateTime> timestampResolved,
            List<Integer> deviceIds, List<Integer> siteIds, List<Integer> siteAccessIds,
            List<Integer> downtimeEventIds, List<Integer> statusIds, List<TaskComment> comments,
            Object recurrence, OptionalNullable<Integer> mainTaskId, TasksResponseAssignee assignee,
            List<MetadataField> metadata) {
        this.taskId = taskId;
        this.title = title;
        this.createdBy = createdBy;
        this.description = description;
        this.category = category;
        this.priority = priority;
        this.timestampStart = timestampStart;
        this.timestampEnd = timestampEnd;
        this.state = state;
        this.resolved = resolved;
        this.timestampResolved = timestampResolved;
        this.deviceIds = deviceIds;
        this.siteIds = siteIds;
        this.siteAccessIds = siteAccessIds;
        this.downtimeEventIds = downtimeEventIds;
        this.statusIds = statusIds;
        this.numberOfComments = numberOfComments;
        this.comments = comments;
        this.recurrence = recurrence;
        this.mainTaskId = mainTaskId;
        this.assignee = assignee;
        this.metadata = metadata;
    }

    /**
     * Getter for TaskId.
     * The id of a task.
     * @return Returns the int
     */
    @JsonGetter("taskId")
    public int getTaskId() {
        return taskId;
    }

    /**
     * Setter for TaskId.
     * The id of a task.
     * @param taskId Value for int
     */
    @JsonSetter("taskId")
    public void setTaskId(int taskId) {
        this.taskId = taskId;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for CreatedBy.
     * @return Returns the User
     */
    @JsonGetter("createdBy")
    public User getCreatedBy() {
        return createdBy;
    }

    /**
     * Setter for CreatedBy.
     * @param createdBy Value for User
     */
    @JsonSetter("createdBy")
    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Internal Getter for Description.
     * @return Returns the Internal String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDescription() {
        return this.description;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    public String getDescription() {
        return OptionalNullable.getFrom(description);
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = OptionalNullable.of(description);
    }

    /**
     * UnSetter for Description.
     */
    public void unsetDescription() {
        description = null;
    }

    /**
     * Getter for Category.
     * @return Returns the Category
     */
    @JsonGetter("category")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Category getCategory() {
        return category;
    }

    /**
     * Setter for Category.
     * @param category Value for Category
     */
    @JsonSetter("category")
    public void setCategory(Category category) {
        this.category = category;
    }

    /**
     * Getter for Priority.
     * @return Returns the TaskPriority
     */
    @JsonGetter("priority")
    public TaskPriority getPriority() {
        return priority;
    }

    /**
     * Setter for Priority.
     * @param priority Value for TaskPriority
     */
    @JsonSetter("priority")
    public void setPriority(TaskPriority priority) {
        this.priority = priority;
    }

    /**
     * Getter for TimestampStart.
     * The timestamp when the task is/was planned to start. The timestamp is in the time zone
     * configured in the Greenbyte Platform without UTC offset.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestampStart")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestampStart() {
        return timestampStart;
    }

    /**
     * Setter for TimestampStart.
     * The timestamp when the task is/was planned to start. The timestamp is in the time zone
     * configured in the Greenbyte Platform without UTC offset.
     * @param timestampStart Value for LocalDateTime
     */
    @JsonSetter("timestampStart")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestampStart(LocalDateTime timestampStart) {
        this.timestampStart = timestampStart;
    }

    /**
     * Getter for TimestampEnd.
     * The timestamp when the is/was planned to end. The timestamp is in the time zone configured in
     * the Greenbyte Platform without UTC offset.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestampEnd")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestampEnd() {
        return timestampEnd;
    }

    /**
     * Setter for TimestampEnd.
     * The timestamp when the is/was planned to end. The timestamp is in the time zone configured in
     * the Greenbyte Platform without UTC offset.
     * @param timestampEnd Value for LocalDateTime
     */
    @JsonSetter("timestampEnd")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestampEnd(LocalDateTime timestampEnd) {
        this.timestampEnd = timestampEnd;
    }

    /**
     * Getter for State.
     * @return Returns the TaskState
     */
    @JsonGetter("state")
    public TaskState getState() {
        return state;
    }

    /**
     * Setter for State.
     * @param state Value for TaskState
     */
    @JsonSetter("state")
    public void setState(TaskState state) {
        this.state = state;
    }

    /**
     * Getter for Resolved.
     * @return Returns the boolean
     */
    @JsonGetter("resolved")
    public boolean getResolved() {
        return resolved;
    }

    /**
     * Setter for Resolved.
     * @param resolved Value for boolean
     */
    @JsonSetter("resolved")
    public void setResolved(boolean resolved) {
        this.resolved = resolved;
    }

    /**
     * Internal Getter for TimestampResolved.
     * The timestamp when the task was resolved. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @return Returns the Internal LocalDateTime
     */
    @JsonGetter("timestampResolved")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Rfc8601DateTimeSerializer.class)
    protected OptionalNullable<LocalDateTime> internalGetTimestampResolved() {
        return this.timestampResolved;
    }

    /**
     * Getter for TimestampResolved.
     * The timestamp when the task was resolved. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @return Returns the LocalDateTime
     */
    public LocalDateTime getTimestampResolved() {
        return OptionalNullable.getFrom(timestampResolved);
    }

    /**
     * Setter for TimestampResolved.
     * The timestamp when the task was resolved. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     * @param timestampResolved Value for LocalDateTime
     */
    @JsonSetter("timestampResolved")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestampResolved(LocalDateTime timestampResolved) {
        this.timestampResolved = OptionalNullable.of(timestampResolved);
    }

    /**
     * UnSetter for TimestampResolved.
     * The timestamp when the task was resolved. The timestamp is in the time zone configured in the
     * Greenbyte Platform without UTC offset.
     */
    public void unsetTimestampResolved() {
        timestampResolved = null;
    }

    /**
     * Getter for DeviceIds.
     * Ids of the devices assigned to the task.
     * @return Returns the List of Integer
     */
    @JsonGetter("deviceIds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getDeviceIds() {
        return deviceIds;
    }

    /**
     * Setter for DeviceIds.
     * Ids of the devices assigned to the task.
     * @param deviceIds Value for List of Integer
     */
    @JsonSetter("deviceIds")
    public void setDeviceIds(List<Integer> deviceIds) {
        this.deviceIds = deviceIds;
    }

    /**
     * Getter for SiteIds.
     * Ids of the sites assigned to the task.
     * @return Returns the List of Integer
     */
    @JsonGetter("siteIds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getSiteIds() {
        return siteIds;
    }

    /**
     * Setter for SiteIds.
     * Ids of the sites assigned to the task.
     * @param siteIds Value for List of Integer
     */
    @JsonSetter("siteIds")
    public void setSiteIds(List<Integer> siteIds) {
        this.siteIds = siteIds;
    }

    /**
     * Getter for SiteAccessIds.
     * Ids of the site accesses linked to the task.
     * @return Returns the List of Integer
     */
    @JsonGetter("siteAccessIds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getSiteAccessIds() {
        return siteAccessIds;
    }

    /**
     * Setter for SiteAccessIds.
     * Ids of the site accesses linked to the task.
     * @param siteAccessIds Value for List of Integer
     */
    @JsonSetter("siteAccessIds")
    public void setSiteAccessIds(List<Integer> siteAccessIds) {
        this.siteAccessIds = siteAccessIds;
    }

    /**
     * Getter for DowntimeEventIds.
     * Ids of the downtime events linked to the task.
     * @return Returns the List of Integer
     */
    @JsonGetter("downtimeEventIds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getDowntimeEventIds() {
        return downtimeEventIds;
    }

    /**
     * Setter for DowntimeEventIds.
     * Ids of the downtime events linked to the task.
     * @param downtimeEventIds Value for List of Integer
     */
    @JsonSetter("downtimeEventIds")
    public void setDowntimeEventIds(List<Integer> downtimeEventIds) {
        this.downtimeEventIds = downtimeEventIds;
    }

    /**
     * Getter for StatusIds.
     * Ids of the statuses linked to the task.
     * @return Returns the List of Integer
     */
    @JsonGetter("statusIds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getStatusIds() {
        return statusIds;
    }

    /**
     * Setter for StatusIds.
     * Ids of the statuses linked to the task.
     * @param statusIds Value for List of Integer
     */
    @JsonSetter("statusIds")
    public void setStatusIds(List<Integer> statusIds) {
        this.statusIds = statusIds;
    }

    /**
     * Getter for NumberOfComments.
     * @return Returns the int
     */
    @JsonGetter("numberOfComments")
    public int getNumberOfComments() {
        return numberOfComments;
    }

    /**
     * Setter for NumberOfComments.
     * @param numberOfComments Value for int
     */
    @JsonSetter("numberOfComments")
    public void setNumberOfComments(int numberOfComments) {
        this.numberOfComments = numberOfComments;
    }

    /**
     * Getter for Comments.
     * The comments belonging to the task.
     * @return Returns the List of TaskComment
     */
    @JsonGetter("comments")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<TaskComment> getComments() {
        return comments;
    }

    /**
     * Setter for Comments.
     * The comments belonging to the task.
     * @param comments Value for List of TaskComment
     */
    @JsonSetter("comments")
    public void setComments(List<TaskComment> comments) {
        this.comments = comments;
    }

    /**
     * Getter for Recurrence.
     * @return Returns the Object
     */
    @JsonGetter("recurrence")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getRecurrence() {
        return recurrence;
    }

    /**
     * Setter for Recurrence.
     * @param recurrence Value for Object
     */
    @JsonSetter("recurrence")
    public void setRecurrence(Object recurrence) {
        this.recurrence = recurrence;
    }

    /**
     * Internal Getter for MainTaskId.
     * @return Returns the Internal Integer
     */
    @JsonGetter("mainTaskId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetMainTaskId() {
        return this.mainTaskId;
    }

    /**
     * Getter for MainTaskId.
     * @return Returns the Integer
     */
    public Integer getMainTaskId() {
        return OptionalNullable.getFrom(mainTaskId);
    }

    /**
     * Setter for MainTaskId.
     * @param mainTaskId Value for Integer
     */
    @JsonSetter("mainTaskId")
    public void setMainTaskId(Integer mainTaskId) {
        this.mainTaskId = OptionalNullable.of(mainTaskId);
    }

    /**
     * UnSetter for MainTaskId.
     */
    public void unsetMainTaskId() {
        mainTaskId = null;
    }

    /**
     * Getter for Assignee.
     * @return Returns the TasksResponseAssignee
     */
    @JsonGetter("assignee")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TasksResponseAssignee getAssignee() {
        return assignee;
    }

    /**
     * Setter for Assignee.
     * @param assignee Value for TasksResponseAssignee
     */
    @JsonSetter("assignee")
    public void setAssignee(TasksResponseAssignee assignee) {
        this.assignee = assignee;
    }

    /**
     * Getter for Metadata.
     * A list of metadata fields and their values.
     * @return Returns the List of MetadataField
     */
    @JsonGetter("metadata")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<MetadataField> getMetadata() {
        return metadata;
    }

    /**
     * Setter for Metadata.
     * A list of metadata fields and their values.
     * @param metadata Value for List of MetadataField
     */
    @JsonSetter("metadata")
    public void setMetadata(List<MetadataField> metadata) {
        this.metadata = metadata;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this TasksResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TasksResponse [" + "taskId=" + taskId + ", title=" + title + ", createdBy="
                + createdBy + ", priority=" + priority + ", timestampStart=" + timestampStart
                + ", timestampEnd=" + timestampEnd + ", state=" + state + ", resolved=" + resolved
                + ", numberOfComments=" + numberOfComments + ", description=" + description
                + ", category=" + category + ", timestampResolved=" + timestampResolved
                + ", deviceIds=" + deviceIds + ", siteIds=" + siteIds + ", siteAccessIds="
                + siteAccessIds + ", downtimeEventIds=" + downtimeEventIds + ", statusIds="
                + statusIds + ", comments=" + comments + ", recurrence=" + recurrence
                + ", mainTaskId=" + mainTaskId + ", assignee=" + assignee + ", metadata=" + metadata
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link TasksResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TasksResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(taskId, title, createdBy, priority, timestampStart,
                timestampEnd, state, resolved, numberOfComments)
                .category(getCategory())
                .deviceIds(getDeviceIds())
                .siteIds(getSiteIds())
                .siteAccessIds(getSiteAccessIds())
                .downtimeEventIds(getDowntimeEventIds())
                .statusIds(getStatusIds())
                .comments(getComments())
                .recurrence(getRecurrence())
                .assignee(getAssignee())
                .metadata(getMetadata());
        builder.description = internalGetDescription();
        builder.timestampResolved = internalGetTimestampResolved();
        builder.mainTaskId = internalGetMainTaskId();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link TasksResponse}.
     */
    public static class Builder {
        private int taskId;
        private String title;
        private User createdBy;
        private TaskPriority priority;
        private LocalDateTime timestampStart;
        private LocalDateTime timestampEnd;
        private TaskState state;
        private boolean resolved;
        private int numberOfComments;
        private OptionalNullable<String> description;
        private Category category;
        private OptionalNullable<LocalDateTime> timestampResolved;
        private List<Integer> deviceIds;
        private List<Integer> siteIds;
        private List<Integer> siteAccessIds;
        private List<Integer> downtimeEventIds;
        private List<Integer> statusIds;
        private List<TaskComment> comments;
        private Object recurrence;
        private OptionalNullable<Integer> mainTaskId;
        private TasksResponseAssignee assignee;
        private List<MetadataField> metadata;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  taskId  int value for taskId.
         * @param  title  String value for title.
         * @param  createdBy  User value for createdBy.
         * @param  priority  TaskPriority value for priority.
         * @param  timestampStart  LocalDateTime value for timestampStart.
         * @param  timestampEnd  LocalDateTime value for timestampEnd.
         * @param  state  TaskState value for state.
         * @param  resolved  boolean value for resolved.
         * @param  numberOfComments  int value for numberOfComments.
         */
        public Builder(int taskId, String title, User createdBy, TaskPriority priority,
                LocalDateTime timestampStart, LocalDateTime timestampEnd, TaskState state,
                boolean resolved, int numberOfComments) {
            this.taskId = taskId;
            this.title = title;
            this.createdBy = createdBy;
            this.priority = priority;
            this.timestampStart = timestampStart;
            this.timestampEnd = timestampEnd;
            this.state = state;
            this.resolved = resolved;
            this.numberOfComments = numberOfComments;
        }

        /**
         * Setter for taskId.
         * @param  taskId  int value for taskId.
         * @return Builder
         */
        public Builder taskId(int taskId) {
            this.taskId = taskId;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for createdBy.
         * @param  createdBy  User value for createdBy.
         * @return Builder
         */
        public Builder createdBy(User createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        /**
         * Setter for priority.
         * @param  priority  TaskPriority value for priority.
         * @return Builder
         */
        public Builder priority(TaskPriority priority) {
            this.priority = priority;
            return this;
        }

        /**
         * Setter for timestampStart.
         * @param  timestampStart  LocalDateTime value for timestampStart.
         * @return Builder
         */
        public Builder timestampStart(LocalDateTime timestampStart) {
            this.timestampStart = timestampStart;
            return this;
        }

        /**
         * Setter for timestampEnd.
         * @param  timestampEnd  LocalDateTime value for timestampEnd.
         * @return Builder
         */
        public Builder timestampEnd(LocalDateTime timestampEnd) {
            this.timestampEnd = timestampEnd;
            return this;
        }

        /**
         * Setter for state.
         * @param  state  TaskState value for state.
         * @return Builder
         */
        public Builder state(TaskState state) {
            this.state = state;
            return this;
        }

        /**
         * Setter for resolved.
         * @param  resolved  boolean value for resolved.
         * @return Builder
         */
        public Builder resolved(boolean resolved) {
            this.resolved = resolved;
            return this;
        }

        /**
         * Setter for numberOfComments.
         * @param  numberOfComments  int value for numberOfComments.
         * @return Builder
         */
        public Builder numberOfComments(int numberOfComments) {
            this.numberOfComments = numberOfComments;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = OptionalNullable.of(description);
            return this;
        }

        /**
         * UnSetter for description.
         * @return Builder
         */
        public Builder unsetDescription() {
            description = null;
            return this;
        }

        /**
         * Setter for category.
         * @param  category  Category value for category.
         * @return Builder
         */
        public Builder category(Category category) {
            this.category = category;
            return this;
        }

        /**
         * Setter for timestampResolved.
         * @param  timestampResolved  LocalDateTime value for timestampResolved.
         * @return Builder
         */
        public Builder timestampResolved(LocalDateTime timestampResolved) {
            this.timestampResolved = OptionalNullable.of(timestampResolved);
            return this;
        }

        /**
         * UnSetter for timestampResolved.
         * @return Builder
         */
        public Builder unsetTimestampResolved() {
            timestampResolved = null;
            return this;
        }

        /**
         * Setter for deviceIds.
         * @param  deviceIds  List of Integer value for deviceIds.
         * @return Builder
         */
        public Builder deviceIds(List<Integer> deviceIds) {
            this.deviceIds = deviceIds;
            return this;
        }

        /**
         * Setter for siteIds.
         * @param  siteIds  List of Integer value for siteIds.
         * @return Builder
         */
        public Builder siteIds(List<Integer> siteIds) {
            this.siteIds = siteIds;
            return this;
        }

        /**
         * Setter for siteAccessIds.
         * @param  siteAccessIds  List of Integer value for siteAccessIds.
         * @return Builder
         */
        public Builder siteAccessIds(List<Integer> siteAccessIds) {
            this.siteAccessIds = siteAccessIds;
            return this;
        }

        /**
         * Setter for downtimeEventIds.
         * @param  downtimeEventIds  List of Integer value for downtimeEventIds.
         * @return Builder
         */
        public Builder downtimeEventIds(List<Integer> downtimeEventIds) {
            this.downtimeEventIds = downtimeEventIds;
            return this;
        }

        /**
         * Setter for statusIds.
         * @param  statusIds  List of Integer value for statusIds.
         * @return Builder
         */
        public Builder statusIds(List<Integer> statusIds) {
            this.statusIds = statusIds;
            return this;
        }

        /**
         * Setter for comments.
         * @param  comments  List of TaskComment value for comments.
         * @return Builder
         */
        public Builder comments(List<TaskComment> comments) {
            this.comments = comments;
            return this;
        }

        /**
         * Setter for recurrence.
         * @param  recurrence  Object value for recurrence.
         * @return Builder
         */
        public Builder recurrence(Object recurrence) {
            this.recurrence = recurrence;
            return this;
        }

        /**
         * Setter for mainTaskId.
         * @param  mainTaskId  Integer value for mainTaskId.
         * @return Builder
         */
        public Builder mainTaskId(Integer mainTaskId) {
            this.mainTaskId = OptionalNullable.of(mainTaskId);
            return this;
        }

        /**
         * UnSetter for mainTaskId.
         * @return Builder
         */
        public Builder unsetMainTaskId() {
            mainTaskId = null;
            return this;
        }

        /**
         * Setter for assignee.
         * @param  assignee  TasksResponseAssignee value for assignee.
         * @return Builder
         */
        public Builder assignee(TasksResponseAssignee assignee) {
            this.assignee = assignee;
            return this;
        }

        /**
         * Setter for metadata.
         * @param  metadata  List of MetadataField value for metadata.
         * @return Builder
         */
        public Builder metadata(List<MetadataField> metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link TasksResponse} object using the set fields.
         * @return {@link TasksResponse}
         */
        public TasksResponse build() {
            TasksResponse model =
                    new TasksResponse(taskId, title, createdBy, priority, timestampStart,
                            timestampEnd, state, resolved, numberOfComments, description, category,
                            timestampResolved, deviceIds, siteIds, siteAccessIds, downtimeEventIds,
                            statusIds, comments, recurrence, mainTaskId, assignee, metadata);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
