/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for TaskCategory type.
 */
public class TaskCategory {
    private int categoryId;
    private String title;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public TaskCategory() {
    }

    /**
     * Initialization constructor.
     * @param  categoryId  int value for categoryId.
     * @param  title  String value for title.
     */
    public TaskCategory(
            int categoryId,
            String title) {
        this.categoryId = categoryId;
        this.title = title;
    }

    /**
     * Getter for CategoryId.
     * The id of a task category.
     * @return Returns the int
     */
    @JsonGetter("categoryId")
    public int getCategoryId() {
        return categoryId;
    }

    /**
     * Setter for CategoryId.
     * The id of a task category.
     * @param categoryId Value for int
     */
    @JsonSetter("categoryId")
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this TaskCategory into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TaskCategory [" + "categoryId=" + categoryId + ", title=" + title
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link TaskCategory.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TaskCategory.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(categoryId, title);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link TaskCategory}.
     */
    public static class Builder {
        private int categoryId;
        private String title;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  categoryId  int value for categoryId.
         * @param  title  String value for title.
         */
        public Builder(int categoryId, String title) {
            this.categoryId = categoryId;
            this.title = title;
        }

        /**
         * Setter for categoryId.
         * @param  categoryId  int value for categoryId.
         * @return Builder
         */
        public Builder categoryId(int categoryId) {
            this.categoryId = categoryId;
            return this;
        }

        /**
         * Setter for title.
         * @param  title  String value for title.
         * @return Builder
         */
        public Builder title(String title) {
            this.title = title;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link TaskCategory} object using the set fields.
         * @return {@link TaskCategory}
         */
        public TaskCategory build() {
            TaskCategory model =
                    new TaskCategory(categoryId, title);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
