/*
 * Greenbyte
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import cloud.greenbyte.intro.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for TasksFilesResponse type.
 */
public class TasksFilesResponse {
    private int fileId;
    private String fileName;
    private LocalDateTime timestampUploaded;
    private User uploadedBy;
    private OptionalNullable<String> description;
    private TaskFileCategory category;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public TasksFilesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  fileId  int value for fileId.
     * @param  fileName  String value for fileName.
     * @param  timestampUploaded  LocalDateTime value for timestampUploaded.
     * @param  uploadedBy  User value for uploadedBy.
     * @param  description  String value for description.
     * @param  category  TaskFileCategory value for category.
     */
    public TasksFilesResponse(
            int fileId,
            String fileName,
            LocalDateTime timestampUploaded,
            User uploadedBy,
            String description,
            TaskFileCategory category) {
        this.fileId = fileId;
        this.fileName = fileName;
        this.timestampUploaded = timestampUploaded;
        this.uploadedBy = uploadedBy;
        this.description = OptionalNullable.of(description);
        this.category = category;
    }

    /**
     * Initialization constructor.
     * @param  fileId  int value for fileId.
     * @param  fileName  String value for fileName.
     * @param  timestampUploaded  LocalDateTime value for timestampUploaded.
     * @param  uploadedBy  User value for uploadedBy.
     * @param  description  String value for description.
     * @param  category  TaskFileCategory value for category.
     */

    protected TasksFilesResponse(int fileId, String fileName, LocalDateTime timestampUploaded,
            User uploadedBy, OptionalNullable<String> description, TaskFileCategory category) {
        this.fileId = fileId;
        this.fileName = fileName;
        this.timestampUploaded = timestampUploaded;
        this.uploadedBy = uploadedBy;
        this.description = description;
        this.category = category;
    }

    /**
     * Getter for FileId.
     * The id of a file.
     * @return Returns the int
     */
    @JsonGetter("fileId")
    public int getFileId() {
        return fileId;
    }

    /**
     * Setter for FileId.
     * The id of a file.
     * @param fileId Value for int
     */
    @JsonSetter("fileId")
    public void setFileId(int fileId) {
        this.fileId = fileId;
    }

    /**
     * Getter for FileName.
     * @return Returns the String
     */
    @JsonGetter("fileName")
    public String getFileName() {
        return fileName;
    }

    /**
     * Setter for FileName.
     * @param fileName Value for String
     */
    @JsonSetter("fileName")
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * Getter for TimestampUploaded.
     * The timestamp when the file was uploaded.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestampUploaded")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestampUploaded() {
        return timestampUploaded;
    }

    /**
     * Setter for TimestampUploaded.
     * The timestamp when the file was uploaded.
     * @param timestampUploaded Value for LocalDateTime
     */
    @JsonSetter("timestampUploaded")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestampUploaded(LocalDateTime timestampUploaded) {
        this.timestampUploaded = timestampUploaded;
    }

    /**
     * Getter for UploadedBy.
     * @return Returns the User
     */
    @JsonGetter("uploadedBy")
    public User getUploadedBy() {
        return uploadedBy;
    }

    /**
     * Setter for UploadedBy.
     * @param uploadedBy Value for User
     */
    @JsonSetter("uploadedBy")
    public void setUploadedBy(User uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    /**
     * Internal Getter for Description.
     * @return Returns the Internal String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDescription() {
        return this.description;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    public String getDescription() {
        return OptionalNullable.getFrom(description);
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = OptionalNullable.of(description);
    }

    /**
     * UnSetter for Description.
     */
    public void unsetDescription() {
        description = null;
    }

    /**
     * Getter for Category.
     * @return Returns the TaskFileCategory
     */
    @JsonGetter("category")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TaskFileCategory getCategory() {
        return category;
    }

    /**
     * Setter for Category.
     * @param category Value for TaskFileCategory
     */
    @JsonSetter("category")
    public void setCategory(TaskFileCategory category) {
        this.category = category;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this TasksFilesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TasksFilesResponse [" + "fileId=" + fileId + ", fileName=" + fileName
                + ", timestampUploaded=" + timestampUploaded + ", uploadedBy=" + uploadedBy
                + ", description=" + description + ", category=" + category
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link TasksFilesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TasksFilesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(fileId, fileName, timestampUploaded, uploadedBy)
                .category(getCategory());
        builder.description = internalGetDescription();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link TasksFilesResponse}.
     */
    public static class Builder {
        private int fileId;
        private String fileName;
        private LocalDateTime timestampUploaded;
        private User uploadedBy;
        private OptionalNullable<String> description;
        private TaskFileCategory category;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  fileId  int value for fileId.
         * @param  fileName  String value for fileName.
         * @param  timestampUploaded  LocalDateTime value for timestampUploaded.
         * @param  uploadedBy  User value for uploadedBy.
         */
        public Builder(int fileId, String fileName, LocalDateTime timestampUploaded,
                User uploadedBy) {
            this.fileId = fileId;
            this.fileName = fileName;
            this.timestampUploaded = timestampUploaded;
            this.uploadedBy = uploadedBy;
        }

        /**
         * Setter for fileId.
         * @param  fileId  int value for fileId.
         * @return Builder
         */
        public Builder fileId(int fileId) {
            this.fileId = fileId;
            return this;
        }

        /**
         * Setter for fileName.
         * @param  fileName  String value for fileName.
         * @return Builder
         */
        public Builder fileName(String fileName) {
            this.fileName = fileName;
            return this;
        }

        /**
         * Setter for timestampUploaded.
         * @param  timestampUploaded  LocalDateTime value for timestampUploaded.
         * @return Builder
         */
        public Builder timestampUploaded(LocalDateTime timestampUploaded) {
            this.timestampUploaded = timestampUploaded;
            return this;
        }

        /**
         * Setter for uploadedBy.
         * @param  uploadedBy  User value for uploadedBy.
         * @return Builder
         */
        public Builder uploadedBy(User uploadedBy) {
            this.uploadedBy = uploadedBy;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = OptionalNullable.of(description);
            return this;
        }

        /**
         * UnSetter for description.
         * @return Builder
         */
        public Builder unsetDescription() {
            description = null;
            return this;
        }

        /**
         * Setter for category.
         * @param  category  TaskFileCategory value for category.
         * @return Builder
         */
        public Builder category(TaskFileCategory category) {
            this.category = category;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link TasksFilesResponse} object using the set fields.
         * @return {@link TasksFilesResponse}
         */
        public TasksFilesResponse build() {
            TasksFilesResponse model =
                    new TasksFilesResponse(fileId, fileName, timestampUploaded, uploadedBy,
                            description, category);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
