/*
 * GreenbyteApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package cloud.greenbyte.intro.models;

import cloud.greenbyte.intro.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for WorklogResponse type.
 */
public class WorklogResponse {
    private Integer worklogItemId;
    private LocalDateTime timestamp;
    private Integer siteId;
    private Double hoursWorked;
    private String comment;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public WorklogResponse() {
    }

    /**
     * Initialization constructor.
     * @param  worklogItemId  Integer value for worklogItemId.
     * @param  timestamp  LocalDateTime value for timestamp.
     * @param  siteId  Integer value for siteId.
     * @param  hoursWorked  Double value for hoursWorked.
     * @param  comment  String value for comment.
     */
    public WorklogResponse(
            Integer worklogItemId,
            LocalDateTime timestamp,
            Integer siteId,
            Double hoursWorked,
            String comment) {
        this.worklogItemId = worklogItemId;
        this.timestamp = timestamp;
        this.siteId = siteId;
        this.hoursWorked = hoursWorked;
        this.comment = comment;
    }

    /**
     * Getter for WorklogItemId.
     * The id of a worklog item.
     * @return Returns the Integer
     */
    @JsonGetter("worklogItemId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getWorklogItemId() {
        return worklogItemId;
    }

    /**
     * Setter for WorklogItemId.
     * The id of a worklog item.
     * @param worklogItemId Value for Integer
     */
    @JsonSetter("worklogItemId")
    public void setWorklogItemId(Integer worklogItemId) {
        this.worklogItemId = worklogItemId;
    }

    /**
     * Getter for Timestamp.
     * The timestamp when the worklog item was entered. The timestamp is in the time zone configured
     * in the Greenbyte Platform without UTC offset.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestamp")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    /**
     * Setter for Timestamp.
     * The timestamp when the worklog item was entered. The timestamp is in the time zone configured
     * in the Greenbyte Platform without UTC offset.
     * @param timestamp Value for LocalDateTime
     */
    @JsonSetter("timestamp")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Getter for SiteId.
     * The id of a site.
     * @return Returns the Integer
     */
    @JsonGetter("siteId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * Setter for SiteId.
     * The id of a site.
     * @param siteId Value for Integer
     */
    @JsonSetter("siteId")
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * Getter for HoursWorked.
     * The number of hours worked on the worklog item.
     * @return Returns the Double
     */
    @JsonGetter("hoursWorked")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getHoursWorked() {
        return hoursWorked;
    }

    /**
     * Setter for HoursWorked.
     * The number of hours worked on the worklog item.
     * @param hoursWorked Value for Double
     */
    @JsonSetter("hoursWorked")
    public void setHoursWorked(Double hoursWorked) {
        this.hoursWorked = hoursWorked;
    }

    /**
     * Getter for Comment.
     * The comment related to the worklog item.
     * @return Returns the String
     */
    @JsonGetter("comment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getComment() {
        return comment;
    }

    /**
     * Setter for Comment.
     * The comment related to the worklog item.
     * @param comment Value for String
     */
    @JsonSetter("comment")
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this WorklogResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "WorklogResponse [" + "worklogItemId=" + worklogItemId + ", timestamp=" + timestamp
                + ", siteId=" + siteId + ", hoursWorked=" + hoursWorked + ", comment=" + comment
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link WorklogResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link WorklogResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .worklogItemId(getWorklogItemId())
                .timestamp(getTimestamp())
                .siteId(getSiteId())
                .hoursWorked(getHoursWorked())
                .comment(getComment());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link WorklogResponse}.
     */
    public static class Builder {
        private Integer worklogItemId;
        private LocalDateTime timestamp;
        private Integer siteId;
        private Double hoursWorked;
        private String comment;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for worklogItemId.
         * @param  worklogItemId  Integer value for worklogItemId.
         * @return Builder
         */
        public Builder worklogItemId(Integer worklogItemId) {
            this.worklogItemId = worklogItemId;
            return this;
        }

        /**
         * Setter for timestamp.
         * @param  timestamp  LocalDateTime value for timestamp.
         * @return Builder
         */
        public Builder timestamp(LocalDateTime timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        /**
         * Setter for siteId.
         * @param  siteId  Integer value for siteId.
         * @return Builder
         */
        public Builder siteId(Integer siteId) {
            this.siteId = siteId;
            return this;
        }

        /**
         * Setter for hoursWorked.
         * @param  hoursWorked  Double value for hoursWorked.
         * @return Builder
         */
        public Builder hoursWorked(Double hoursWorked) {
            this.hoursWorked = hoursWorked;
            return this;
        }

        /**
         * Setter for comment.
         * @param  comment  String value for comment.
         * @return Builder
         */
        public Builder comment(String comment) {
            this.comment = comment;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link WorklogResponse} object using the set fields.
         * @return {@link WorklogResponse}
         */
        public WorklogResponse build() {
            WorklogResponse model =
                    new WorklogResponse(worklogItemId, timestamp, siteId, hoursWorked, comment);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
